INSERT INTO `_traducciones` (`id`, `frase`, `idioma`, `traduccion`) VALUES 
(null, 'export_sql', 'es_ES', 'export_sql'),
(null, 'Detalles del pedido', 'es_ES', 'Detalles del pedido'),
(null, 'implant', 'es_ES', 'implant'),
(null, 'coude_soupe', 'es_ES', 'coude_soupe'),
(null, 'fil_nylon', 'es_ES', 'fil_nylon'),
(null, 'pailletes', 'es_ES', 'pailletes'),
(null, 'cordon', 'es_ES', 'cordon'),
(null, 'hoka', 'es_ES', 'hoka'),
(null, 'mix', 'es_ES', 'mix'),
(null, 'anti_bacterie', 'es_ES', 'anti_bacterie'),
(null, 'thermosoft', 'es_ES', 'thermosoft'),
(null, 'thermotec', 'es_ES', 'thermotec'),
(null, 'silicone', 'es_ES', 'silicone'),
(null, 'resine', 'es_ES', 'resine'),
(null, 'iros', 'es_ES', 'iros'),
(null, 'prince_de_crave', 'es_ES', 'prince_de_crave'),
(null, 'epaulemnent', 'es_ES', 'epaulemnent'),
(null, 'conduit_seul', 'es_ES', 'conduit_seul'),
(null, 'coquille', 'es_ES', 'coquille'),
(null, 'invisible', 'es_ES', 'invisible'),
(null, 'anti_bruit', 'es_ES', 'anti_bruit'),
(null, 'dormir', 'es_ES', 'dormir'),
(null, 'natation', 'es_ES', 'natation'),
(null, 'custom_dume', 'es_ES', 'custom_dume'),
(null, 'slim_tube', 'es_ES', 'slim_tube'),
(null, 'rite', 'es_ES', 'rite'),
(null, 'bte', 'es_ES', 'bte'),
(null, 'dure', 'es_ES', 'dure'),
(null, 'molle', 'es_ES', 'molle'),
(null, 'grave', 'es_ES', 'grave'),
(null, 'moyenne', 'es_ES', 'moyenne'),
(null, 'legere', 'es_ES', 'legere'),
(null, 'remake', 'es_ES', 'remake'),
(null, 'payant', 'es_ES', 'payant'),
(null, 'Nuevo pedido vía la web', 'es_ES', 'Nuevo pedido vía la web'),
(null, 'notes', 'es_ES', 'Notas'),
(null, 'couleur_droite', 'es_ES', 'Color Der.'),
(null, 'models', 'es_ES', 'Modelos'),
(null, 'marques', 'es_ES', 'Marcas'),
(null, 'couleur_gauche', 'es_ES', 'Color Izq.'),
(null, 'ventilation_droite', 'es_ES', 'Ventilación der.'),
(null, 'ventilation_gauche', 'es_ES', 'Ventilación izq.'),
(null, 'du_numero', 'es_ES', 'De número'),
(null, 'pedidos_cliente', 'es_ES', 'Nombre del cliente'),
(null, 'pedidos_empresa', 'es_ES', 'Empresa'),
(null, 'pedidos_fecha', 'es_ES', 'Fecha del pedido'),
(null, 'pedidos_email', 'es_ES', 'Email'),
(null, 'pedidos_ref', 'es_ES', 'Referencia'),
(null, 'a', 'es_ES', 'a'),
(null, 'c', 'es_ES', 'c'),
(null, 'p', 'es_ES', 'p'),
(null, 'Lista de logs', 'es_ES', 'Lista de logs'),
(null, 'Id_pedido', 'es_ES', 'Id_pedido'),
(null, 'logs', 'es_ES', 'logs'),
(null, 'Argumento', 'es_ES', 'Argumento'),
(null, 'Pedido', 'es_ES', 'Pedido'),
(null, 'A', 'es_ES', 'A'),
(null, 'C', 'es_ES', 'C'),
(null, 'P', 'es_ES', 'P'),
(null, 'Nuevo logs', 'es_ES', 'Nuevo logs'),
(null, 'Todos', 'es_ES', 'Todos'),
(null, 'Acción', 'es_ES', 'Acción'),
(null, 'Página', 'es_ES', 'Página'),
(null, 'sin permiso', 'es_ES', 'sin permiso'),
(null, 'Mis pedidos', 'es_ES', 'Mis pedidos'),
(null, 'Estatus del pedidoBorrado', 'es_ES', 'Estatus del pedidoBorrado'),
(null, 'Ya no puede editar este pedido', 'es_ES', 'Ya no puede editar este pedido'),
(null, 'El pedido esta en siendo tratado, ya no puede editarlo', 'es_ES', 'El pedido esta en siendo tratado, ya no puede editarlo'),
(null, 'El pedido esta en siendo tratado', 'es_ES', 'El pedido esta en siendo tratado'),
(null, 'buscar_segun_estatus', 'es_ES', 'buscar_segun_estatus'),
(null, 'cambiar_estatus', 'es_ES', 'cambiar_estatus'),
(null, 'Borrado', 'es_ES', 'Borrado'),
(null, 'Enviado', 'es_ES', 'Enviado'),
(null, 'Borrar', 'es_ES', 'Borrar'),
(null, 'Enviado a cliente', 'es_ES', 'Enviado a cliente'),
(null, 'En proceso', 'es_ES', 'En proceso'),
(null, 'Registrado', 'es_ES', 'Registrado'),
(null, 'Formato texto', 'es_ES', 'Formato texto'),
(null, 'Bon n°:', 'es_ES', 'Bon n°:'),
(null, 'Bon n:', 'es_ES', 'Bon n:'),
(null, 'Busqueda detallada', 'es_ES', 'Busqueda detallada'),
(null, 'Número no existe', 'es_ES', 'Número no existe'),
(null, 'Pedidos Editar', 'es_ES', 'Pedidos Editar'),
(null, 'Mix', 'es_ES', 'Mix'),
(null, 'borrarr', 'es_ES', 'borrarr'),
(null, 'borrar', 'es_ES', 'borrar'),
(null, 'Pedido no le pertenece', 'es_ES', 'Pedido no le pertenece'),
(null, 'Bloqueado, No puede realizar pedidos', 'es_ES', 'Bloqueado, No puede realizar pedidos'),
(null, 'Activo, puede realizar pedidos', 'es_ES', 'Activo, puede realizar pedidos'),
(null, 'Cuenta bloqueada, no puede realizar pedidos', 'es_ES', 'Cuenta bloqueada, no puede realizar pedidos'),
(null, '-', 'es_ES', '-'),
(null, 'Por defecto se asignara el grupo centros a todo nuevo usuario', 'es_ES', 'Por defecto se asignara el grupo centros a todo nuevo usuario'),
(null, 'Usuarios', 'es_ES', 'Usuarios'),
(null, 't_usuarios', 'es_ES', 't_usuarios'),
(null, 'No se puede agregar usuarios root', 'es_ES', 'No se puede agregar usuarios root'),
(null, 'Olvido el email', 'es_ES', 'Olvido el email'),
(null, 'Editar _usuarios', 'es_ES', 'Editar _usuarios'),
(null, 'Olvido email', 'es_ES', 'Olvido email'),
(null, 'Email ya existe en la base de datos', 'es_ES', 'Email ya existe en la base de datos'),
(null, 'esss', 'es_ES', 'esss'),
(null, 'Si un cliente ya tiene pedidos registrados, no se puede cambiar de email', 'es_ES', 'Si un cliente ya tiene pedidos registrados, no se puede cambiar de email'),
(null, 'Pedidos', 'es_ES', 'Pedidos'),
(null, 'No, crear uno.', 'es_ES', 'No, crear uno.'),
(null, 'Este pedido no le pertenece', 'es_ES', 'Este pedido no le pertenece'),
(null, 'Nuevo cliente', 'es_ES', 'Nuevo cliente'),
(null, 'País', 'es_ES', 'País'),
(null, 'Dirección', 'es_ES', 'Dirección'),
(null, 'Empresa SPRL', 'es_ES', 'Empresa SPRL'),
(null, 'Belgique', 'es_ES', 'Belgique'),
(null, 'Código postal', 'es_ES', 'Código postal'),
(null, 'Sr. Sra. Srta. Dr. Dra. ...', 'es_ES', 'Sr. Sra. Srta. Dr. Dra. ...'),
(null, 'Nombres y apellidos', 'es_ES', 'Nombres y apellidos'),
(null, '123.123.123', 'es_ES', '123.123.123'),
(null, 'TVA', 'es_ES', 'TVA'),
(null, 'No, crear uno', 'es_ES', 'No, crear uno'),
(null, 'Para que un usuario tenga un login, debe estar registrado primero en la lista de <a href="index.php?p=clientes&c=index">clientes</a>, si el cliente ya tiene un login no aparecera en esta lista', 'es_ES', 'Para que un usuario tenga un login, debe estar registrado primero en la lista de <a href="index.php?p=clientes&c=index">clientes</a>, si el cliente ya tiene un login no aparecera en esta lista'),
(null, 'Clientes sin usuario', 'es_ES', 'Clientes sin usuario'),
(null, 'Para que un usuario tenga un login, debe estar registrado primero en la lista de <a href="index.php?p=clientes&c=index">clientes</a>', 'es_ES', 'Para que un usuario tenga un login, debe estar registrado primero en la lista de <a href="index.php?p=clientes&c=index">clientes</a>'),
(null, 'Para que un usuario tenga un login, debe estar registrado primero en la lista de clientes', 'es_ES', 'Para que un usuario tenga un login, debe estar registrado primero en la lista de clientes'),
(null, 'Nuevo usuario en el sistema', 'es_ES', 'Nuevo usuario en el sistema'),
(null, 'Tiene login', 'es_ES', 'Tiene login'),
(null, 'Si', 'es_ES', 'Si'),
(null, 'No', 'es_ES', 'No'),
(null, 'Nuevo usuario', 'es_ES', 'Nuevo usuario'),
(null, 'Lista de usuarios', 'es_ES', 'Lista de usuarios'),
(null, 'Resultados de su busqueda', 'es_ES', 'Resultados de su busqueda'),
(null, 'Ver', 'es_ES', 'Ver'),
(null, 'Repita aca la nueva clave', 'es_ES', 'Repita aca la nueva clave'),
(null, 'Letras, números, signos [&é#§çà, etc]', 'es_ES', 'Letras, números, signos [&é#§çà, etc]'),
(null, 'Letras, números, signos[&é#§çà, etc]', 'es_ES', 'Letras, números, signos[&é#§çà, etc]'),
(null, 'Su clave actual', 'es_ES', 'Su clave actual'),
(null, 'Repita', 'es_ES', 'Repita'),
(null, 'Nueva clave', 'es_ES', 'Nueva clave'),
(null, 'Clave Actual', 'es_ES', 'Clave Actual'),
(null, '123, sin ceros al inicio', 'es_ES', '123, sin ceros al inicio'),
(null, 'Bon', 'es_ES', 'Bon'),
(null, 'Id', 'es_ES', 'Id'),
(null, 'Editar _grupos', 'es_ES', 'Editar _grupos'),
(null, 'Grupos que el sistema tiene', 'es_ES', 'Grupos que el sistema tiene'),
(null, 'Una mala manipulación puede comprometer la seguridad de su sistema', 'es_ES', 'Una mala manipulación puede comprometer la seguridad de su sistema'),
(null, 'Si no esta seguro, no modifique nada porfavor', 'es_ES', 'Si no esta seguro, no modifique nada porfavor'),
(null, 'ID', 'es_ES', 'ID'),
(null, 'Editar clientes', 'es_ES', 'Editar clientes'),
(null, 'Tva', 'es_ES', 'Tva'),
(null, 'Login', 'es_ES', 'Login'),
(null, 'Av. Louise 265', 'es_ES', 'Av. Louise 265'),
(null, 'Bruxelles', 'es_ES', 'Bruxelles'),
(null, '1000', 'es_ES', '1000'),
(null, '123.456.789', 'es_ES', '123.456.789'),
(null, 'info@mail.com', 'es_ES', 'info@mail.com'),
(null, '+322123456', 'es_ES', '+322123456'),
(null, 'Número TVA', 'es_ES', 'Número TVA'),
(null, 'Numero TVA', 'es_ES', 'Numero TVA'),
(null, '000.111.222', 'es_ES', '000.111.222'),
(null, 'BE', 'es_ES', 'BE'),
(null, 'Numero de tva', 'es_ES', 'Numero de tva'),
(null, 'Nuevo clientes', 'es_ES', 'Nuevo clientes'),
(null, 'Es cliente', 'es_ES', 'Es cliente'),
(null, 'Fecha registro', 'es_ES', 'Fecha registro'),
(null, 'Numero documento', 'es_ES', 'Numero documento'),
(null, 'Ruc prefijo', 'es_ES', 'Ruc prefijo'),
(null, 'Tipo documento', 'es_ES', 'Tipo documento'),
(null, 'Lista de clientes', 'es_ES', 'Lista de clientes'),
(null, 'Estrellas', 'es_ES', 'Estrellas'),
(null, 'Es_cliente', 'es_ES', 'Es_cliente'),
(null, 'Fecha_registro', 'es_ES', 'Fecha_registro'),
(null, 'Tipo', 'es_ES', 'Tipo'),
(null, 'Fax', 'es_ES', 'Fax'),
(null, 'Tel', 'es_ES', 'Tel'),
(null, 'Pais', 'es_ES', 'Pais'),
(null, 'Provincia', 'es_ES', 'Provincia'),
(null, 'Ciudad', 'es_ES', 'Ciudad'),
(null, 'Cpostal', 'es_ES', 'Cpostal'),
(null, 'Direccion', 'es_ES', 'Direccion'),
(null, 'Saludo', 'es_ES', 'Saludo'),
(null, 'Numero_documento', 'es_ES', 'Numero_documento'),
(null, 'Ruc_prefijo', 'es_ES', 'Ruc_prefijo'),
(null, 'Tipo_documento', 'es_ES', 'Tipo_documento'),
(null, 'clientes', 'es_ES', 'clientes'),
(null, 'txt', 'es_ES', 'txt'),
(null, 'Editar pedidos', 'es_ES', 'Editar pedidos'),
(null, 'email', 'es_ES', 'email'),
(null, 'Al crear un nuevo grupo debe también configurar los permisos que este tendra en el sistema', 'es_ES', 'Al crear un nuevo grupo debe también configurar los permisos que este tendra en el sistema'),
(null, '', 'es_ES', ''),
(null, 'Editar _traducciones', 'es_ES', 'Editar _traducciones'),
(null, 'Nuevo _traducciones', 'es_ES', 'Nuevo _traducciones'),
(null, 'Registrar idioma', 'es_ES', 'Registrar idioma'),
(null, 'xx_XX', 'es_ES', 'xx_XX'),
(null, 'Idiomas', 'es_ES', 'Idiomas'),
(null, 'Esta acción puede comprometar la seguridad de su web, esta seguro?', 'es_ES', 'Esta acción puede comprometar la seguridad de su web, esta seguro?'),
(null, 'Editar _contenido', 'es_ES', 'Editar _contenido'),
(null, 'Editar _permisos', 'es_ES', 'Editar _permisos'),
(null, 'Nuevo _permisos', 'es_ES', 'Nuevo _permisos'),
(null, 'Nuevo _grupos', 'es_ES', 'Nuevo _grupos'),
(null, 'Contacte con el administrador', 'es_ES', 'Contacte con el administrador'),
(null, 'No disponible', 'es_ES', 'No disponible'),
(null, 'Ok', 'es_ES', 'Ok'),
(null, 'Info', 'es_ES', 'Info'),
(null, 'Alto', 'es_ES', 'Alto'),
(null, 'Ayuda', 'es_ES', 'Ayuda'),
(null, 'Atención', 'es_ES', 'Atención'),
(null, 'cambiar_clave', 'es_ES', 'cambiar_clave'),
(null, 'users', 'es_ES', 'users'),
(null, 'Nuevo', 'es_ES', 'Nuevo'),
(null, 'Nuevo _paginas', 'es_ES', 'Nuevo _paginas'),
(null, 'Editar _paginas', 'es_ES', 'Editar _paginas'),
(null, 'ver', 'es_ES', 'ver'),
(null, 'Nuevo _contenido', 'es_ES', 'Nuevo _contenido'),
(null, 'Lista de _traducciones', 'es_ES', 'Lista de _traducciones'),
(null, 'Traduccion', 'es_ES', 'Traduccion'),
(null, '_traducciones', 'es_ES', '_traducciones'),
(null, 'Lista de _paginas', 'es_ES', 'Lista de _paginas'),
(null, 'Nuevo _idiomas', 'es_ES', 'Nuevo _idiomas'),
(null, 'Resultados de su busqueda en ', 'es_ES', 'Resultados de su busqueda en '),
(null, 'buscar', 'es_ES', 'buscar'),
(null, 'Enviar', 'es_ES', 'Enviar'),
(null, 'Implante', 'es_ES', 'Implante'),
(null, 'Codo suave', 'es_ES', 'Codo suave'),
(null, 'Fil nylon', 'es_ES', 'Fil nylon'),
(null, 'Pailletes', 'es_ES', 'Pailletes'),
(null, 'Cordon', 'es_ES', 'Cordon'),
(null, 'Hoka', 'es_ES', 'Hoka'),
(null, 'Opciones', 'es_ES', 'Opciones'),
(null, 'Color derecha', 'es_ES', 'Color derecha'),
(null, 'Models', 'es_ES', 'Models'),
(null, 'Marques', 'es_ES', 'Marques'),
(null, 'RITE / SLIM TUBE', 'es_ES', 'RITE / SLIM TUBE'),
(null, 'Color izquierda', 'es_ES', 'Color izquierda'),
(null, 'Derecha', 'es_ES', 'Derecha'),
(null, 'Ventilation Droite', 'es_ES', 'Ventilation Droite'),
(null, 'Izquierda', 'es_ES', 'Izquierda'),
(null, 'Ventilación', 'es_ES', 'Ventilación'),
(null, 'Otro 2', 'es_ES', 'Otro 2'),
(null, 'Otro 1', 'es_ES', 'Otro 1'),
(null, 'Anti-Bactérie', 'es_ES', 'Anti-Bactérie'),
(null, 'Thermosoft', 'es_ES', 'Thermosoft'),
(null, 'Thermotec', 'es_ES', 'Thermotec'),
(null, 'Silicone', 'es_ES', 'Silicone'),
(null, 'Résine', 'es_ES', 'Résine'),
(null, 'Materiales', 'es_ES', 'Materiales'),
(null, 'Otro', 'es_ES', 'Otro'),
(null, 'Iros', 'es_ES', 'Iros'),
(null, 'Prince de Crave', 'es_ES', 'Prince de Crave'),
(null, 'Epaulement', 'es_ES', 'Epaulement'),
(null, 'Conduit seul', 'es_ES', 'Conduit seul'),
(null, 'Coquille', 'es_ES', 'Coquille'),
(null, 'Invisible', 'es_ES', 'Invisible'),
(null, 'Modelos', 'es_ES', 'Modelos'),
(null, 'Anti ruido', 'es_ES', 'Anti ruido'),
(null, 'Dormir', 'es_ES', 'Dormir'),
(null, 'Natation', 'es_ES', 'Natation'),
(null, 'Custom Dume', 'es_ES', 'Custom Dume'),
(null, 'Slim Tube', 'es_ES', 'Slim Tube'),
(null, 'Rite', 'es_ES', 'Rite'),
(null, 'Bte', 'es_ES', 'Bte'),
(null, 'Tipos', 'es_ES', 'Tipos'),
(null, 'Dura', 'es_ES', 'Dura'),
(null, 'Suave', 'es_ES', 'Suave'),
(null, 'Construcción orejera', 'es_ES', 'Construcción orejera'),
(null, 'Grave', 'es_ES', 'Grave'),
(null, 'Media', 'es_ES', 'Media'),
(null, 'Ligera', 'es_ES', 'Ligera'),
(null, 'Perdida auditiva', 'es_ES', 'Perdida auditiva'),
(null, 'De n°', 'es_ES', 'De n°'),
(null, 'Remake', 'es_ES', 'Remake'),
(null, 'Payant', 'es_ES', 'Payant'),
(null, 'Nombre del cliente', 'es_ES', 'Nombre del cliente'),
(null, 'Centro auditivo', 'es_ES', 'Centro auditivo'),
(null, 'Bon n°', 'es_ES', 'Bon n°'),
(null, 'Detalles', 'es_ES', 'Detalles'),
(null, 'Editar', 'es_ES', 'Editar'),
(null, 'Editar _menu', 'es_ES', 'Editar _menu'),
(null, 'editar', 'es_ES', 'editar'),
(null, 'Nuevo _menu', 'es_ES', 'Nuevo _menu'),
(null, 'Lista de _menu', 'es_ES', 'Lista de _menu'),
(null, 'Orden', 'es_ES', 'Orden'),
(null, 'Icono', 'es_ES', 'Icono'),
(null, 'Url', 'es_ES', 'Url'),
(null, 'Label', 'es_ES', 'Label'),
(null, 'Padre', 'es_ES', 'Padre'),
(null, 'Ubicacion', 'es_ES', 'Ubicacion'),
(null, '_paginas', 'es_ES', '_paginas'),
(null, '_menu', 'es_ES', '_menu'),
(null, 'Lista de _permisos', 'es_ES', 'Lista de _permisos'),
(null, 'Permiso', 'es_ES', 'Permiso'),
(null, 'Pagina', 'es_ES', 'Pagina'),
(null, '_permisos', 'es_ES', '_permisos'),
(null, 'Lista de _idiomas', 'es_ES', 'Lista de _idiomas'),
(null, 'Nombre', 'es_ES', 'Nombre'),
(null, 'Idioma', 'es_ES', 'Idioma'),
(null, '_idiomas', 'es_ES', '_idiomas'),
(null, 'Nuevo _usuarios', 'es_ES', 'Nuevo _usuarios'),
(null, 'Lista de _usuarios', 'es_ES', 'Lista de _usuarios'),
(null, 'Clave', 'es_ES', 'Clave'),
(null, 'Usuario', 'es_ES', 'Usuario'),
(null, '_usuarios', 'es_ES', '_usuarios'),
(null, 'Registrar', 'es_ES', 'Registrar'),
(null, 'Bloqueado', 'es_ES', 'Bloqueado'),
(null, 'Activo', 'es_ES', 'Activo'),
(null, 'aaaa-mm-dd', 'es_ES', 'aaaa-mm-dd'),
(null, 'Nuevo pedidos', 'es_ES', 'Nuevo pedidos'),
(null, 'crear', 'es_ES', 'crear'),
(null, 'Lista de pedidos', 'es_ES', 'Lista de pedidos'),
(null, 'Estatus', 'es_ES', 'Estatus'),
(null, 'Notas', 'es_ES', 'Notas'),
(null, 'Fecha', 'es_ES', 'Fecha'),
(null, 'Descripcion', 'es_ES', 'Descripcion'),
(null, 'Email', 'es_ES', 'Email'),
(null, 'Cliente', 'es_ES', 'Cliente'),
(null, 'Empresa', 'es_ES', 'Empresa'),
(null, 'Ref', 'es_ES', 'Ref'),
(null, 'pedidos', 'es_ES', 'pedidos'),
(null, 'Lista de _grupos', 'es_ES', 'Lista de _grupos'),
(null, 'Grupo', 'es_ES', 'Grupo'),
(null, '_grupos', 'es_ES', '_grupos'),
(null, 'Accion', 'es_ES', 'Accion'),
(null, 'Nueva', 'es_ES', 'Nueva'),
(null, 'Lista de _contenido', 'es_ES', 'Lista de _contenido'),
(null, 'Contexto', 'es_ES', 'Contexto'),
(null, 'Frase', 'es_ES', 'Frase'),
(null, 'Buscar', 'es_ES', 'Buscar'),
(null, 'Lista', 'es_ES', 'Lista'),
(null, '_contenido', 'es_ES', '_contenido'),
(null, 'index', 'es_ES', 'index'),
(null, 'home', 'es_ES', 'home'),
(null, 'Inicio', 'es_ES', 'Inicio'),
(null, 'Logout', 'es_ES', 'Logout'),
(null, 'Cambiar clave', 'es_ES', 'Cambiar clave')
;    

