INSERT INTO `_traducciones` (`id`, `frase`, `idioma`, `traduccion`) VALUES 
(null, 'export_sql', 'fr_BE', 'export_sql'),
(null, 'Detalles del pedido', 'fr_BE', 'Détails de la commande'),
(null, 'implant', 'fr_BE', 'implant'),
(null, 'coude_soupe', 'fr_BE', 'coude_soupe'),
(null, 'fil_nylon', 'fr_BE', 'fil_nylon'),
(null, 'pailletes', 'fr_BE', 'pailletes'),
(null, 'cordon', 'fr_BE', 'cordon'),
(null, 'hoka', 'fr_BE', 'hoka'),
(null, 'mix', 'fr_BE', 'mix'),
(null, 'anti_bacterie', 'fr_BE', 'anti_bacterie'),
(null, 'thermosoft', 'fr_BE', 'thermosoft'),
(null, 'thermotec', 'fr_BE', 'thermotec'),
(null, 'silicone', 'fr_BE', 'silicone'),
(null, 'resine', 'fr_BE', 'resine'),
(null, 'iros', 'fr_BE', 'iros'),
(null, 'prince_de_crave', 'fr_BE', 'prince_de_crave'),
(null, 'epaulemnent', 'fr_BE', 'epaulemnent'),
(null, 'conduit_seul', 'fr_BE', 'conduit_seul'),
(null, 'coquille', 'fr_BE', 'coquille'),
(null, 'invisible', 'fr_BE', 'invisible'),
(null, 'anti_bruit', 'fr_BE', 'anti_bruit'),
(null, 'dormir', 'fr_BE', 'dormir'),
(null, 'natation', 'fr_BE', 'natation'),
(null, 'custom_dume', 'fr_BE', 'custom_dume'),
(null, 'slim_tube', 'fr_BE', 'slim_tube'),
(null, 'rite', 'fr_BE', 'rite'),
(null, 'bte', 'fr_BE', 'bte'),
(null, 'dure', 'fr_BE', 'dure'),
(null, 'molle', 'fr_BE', 'molle'),
(null, 'grave', 'fr_BE', 'grave'),
(null, 'moyenne', 'fr_BE', 'moyenne'),
(null, 'legere', 'fr_BE', 'legere'),
(null, 'remake', 'fr_BE', 'remake'),
(null, 'payant', 'fr_BE', 'payant'),
(null, 'Nuevo pedido vía la web', 'fr_BE', 'Nuevo pedido vía la web'),
(null, 'notes', 'fr_BE', 'Notas'),
(null, 'couleur_droite', 'fr_BE', 'Color Der.'),
(null, 'models', 'fr_BE', 'Modelos'),
(null, 'marques', 'fr_BE', 'Marcas'),
(null, 'couleur_gauche', 'fr_BE', 'Color Izq.'),
(null, 'ventilation_droite', 'fr_BE', 'Ventilación der.'),
(null, 'ventilation_gauche', 'fr_BE', 'Ventilación izq.'),
(null, 'du_numero', 'fr_BE', 'De número'),
(null, 'pedidos_cliente', 'fr_BE', 'Nombre del cliente'),
(null, 'pedidos_empresa', 'fr_BE', 'Empresa'),
(null, 'pedidos_fecha', 'fr_BE', 'Fecha del pedido'),
(null, 'pedidos_email', 'fr_BE', 'Email'),
(null, 'pedidos_ref', 'fr_BE', 'Referencia'),
(null, 'a', 'fr_BE', 'a'),
(null, 'c', 'fr_BE', 'c'),
(null, 'p', 'fr_BE', 'p'),
(null, 'Lista de logs', 'fr_BE', 'Lista de logs'),
(null, 'Id_pedido', 'fr_BE', 'Id_pedido'),
(null, 'logs', 'fr_BE', 'logs'),
(null, 'Argumento', 'fr_BE', 'Argumento'),
(null, 'Pedido', 'fr_BE', 'Pedido'),
(null, 'A', 'fr_BE', 'A'),
(null, 'C', 'fr_BE', 'C'),
(null, 'P', 'fr_BE', 'P'),
(null, 'Nuevo logs', 'fr_BE', 'Nuevo logs'),
(null, 'Todos', 'fr_BE', 'Todos'),
(null, 'Acción', 'fr_BE', 'Acción'),
(null, 'Página', 'fr_BE', 'Página'),
(null, 'sin permiso', 'fr_BE', 'sin permiso'),
(null, 'Mis pedidos', 'fr_BE', 'Mis pedidos'),
(null, 'Estatus del pedidoBorrado', 'fr_BE', 'Estatus del pedidoBorrado'),
(null, 'Ya no puede editar este pedido', 'fr_BE', 'Ya no puede editar este pedido'),
(null, 'El pedido esta en siendo tratado, ya no puede editarlo', 'fr_BE', 'El pedido esta en siendo tratado, ya no puede editarlo'),
(null, 'El pedido esta en siendo tratado', 'fr_BE', 'El pedido esta en siendo tratado'),
(null, 'buscar_segun_estatus', 'fr_BE', 'buscar_segun_estatus'),
(null, 'cambiar_estatus', 'fr_BE', 'cambiar_estatus'),
(null, 'Borrado', 'fr_BE', 'Borrado'),
(null, 'Enviado', 'fr_BE', 'Enviado'),
(null, 'Borrar', 'fr_BE', 'Borrar'),
(null, 'Enviado a cliente', 'fr_BE', 'Enviado a cliente'),
(null, 'En proceso', 'fr_BE', 'En proceso'),
(null, 'Registrado', 'fr_BE', 'Registrado'),
(null, 'Formato texto', 'fr_BE', 'Formato texto'),
(null, 'Bon n°:', 'fr_BE', 'Bon n°:'),
(null, 'Bon n:', 'fr_BE', 'Bon n:'),
(null, 'Busqueda detallada', 'fr_BE', 'Busqueda detallada'),
(null, 'Número no existe', 'fr_BE', 'Número no existe'),
(null, 'Pedidos Editar', 'fr_BE', 'Pedidos Editar'),
(null, 'Mix', 'fr_BE', 'Mix'),
(null, 'borrarr', 'fr_BE', 'borrarr'),
(null, 'borrar', 'fr_BE', 'borrar'),
(null, 'Pedido no le pertenece', 'fr_BE', 'Pedido no le pertenece'),
(null, 'Bloqueado, No puede realizar pedidos', 'fr_BE', 'Bloqueado, No puede realizar pedidos'),
(null, 'Activo, puede realizar pedidos', 'fr_BE', 'Activo, puede realizar pedidos'),
(null, 'Cuenta bloqueada, no puede realizar pedidos', 'fr_BE', 'Cuenta bloqueada, no puede realizar pedidos'),
(null, '-', 'fr_BE', '-'),
(null, 'Por defecto se asignara el grupo centros a todo nuevo usuario', 'fr_BE', 'Por defecto se asignara el grupo centros a todo nuevo usuario'),
(null, 'Usuarios', 'fr_BE', 'Usuarios'),
(null, 't_usuarios', 'fr_BE', 't_usuarios'),
(null, 'No se puede agregar usuarios root', 'fr_BE', 'No se puede agregar usuarios root'),
(null, 'Olvido el email', 'fr_BE', 'Olvido el email'),
(null, 'Editar _usuarios', 'fr_BE', 'Editar _usuarios'),
(null, 'Olvido email', 'fr_BE', 'Olvido email'),
(null, 'Email ya existe en la base de datos', 'fr_BE', 'Email ya existe en la base de datos'),
(null, 'esss', 'fr_BE', 'esss'),
(null, 'Si un cliente ya tiene pedidos registrados, no se puede cambiar de email', 'fr_BE', 'Si un cliente ya tiene pedidos registrados, no se puede cambiar de email'),
(null, 'Pedidos', 'fr_BE', 'Pedidos'),
(null, 'No, crear uno.', 'fr_BE', 'No, crear uno.'),
(null, 'Este pedido no le pertenece', 'fr_BE', 'Este pedido no le pertenece'),
(null, 'Nuevo cliente', 'fr_BE', 'Nuevo cliente'),
(null, 'País', 'fr_BE', 'País'),
(null, 'Dirección', 'fr_BE', 'Dirección'),
(null, 'Empresa SPRL', 'fr_BE', 'Empresa SPRL'),
(null, 'Belgique', 'fr_BE', 'Belgique'),
(null, 'Código postal', 'fr_BE', 'Código postal'),
(null, 'Sr. Sra. Srta. Dr. Dra. ...', 'fr_BE', 'Sr. Sra. Srta. Dr. Dra. ...'),
(null, 'Nombres y apellidos', 'fr_BE', 'Nombres y apellidos'),
(null, '123.123.123', 'fr_BE', '123.123.123'),
(null, 'TVA', 'fr_BE', 'TVA'),
(null, 'No, crear uno', 'fr_BE', 'No, crear uno'),
(null, 'Para que un usuario tenga un login, debe estar registrado primero en la lista de <a href="index.php?p=clientes&c=index">clientes</a>, si el cliente ya tiene un login no aparecera en esta lista', 'fr_BE', 'Para que un usuario tenga un login, debe estar registrado primero en la lista de <a href="index.php?p=clientes&c=index">clientes</a>, si el cliente ya tiene un login no aparecera en esta lista'),
(null, 'Clientes sin usuario', 'fr_BE', 'Clientes sin usuario'),
(null, 'Para que un usuario tenga un login, debe estar registrado primero en la lista de <a href="index.php?p=clientes&c=index">clientes</a>', 'fr_BE', 'Para que un usuario tenga un login, debe estar registrado primero en la lista de <a href="index.php?p=clientes&c=index">clientes</a>'),
(null, 'Para que un usuario tenga un login, debe estar registrado primero en la lista de clientes', 'fr_BE', 'Para que un usuario tenga un login, debe estar registrado primero en la lista de clientes'),
(null, 'Nuevo usuario en el sistema', 'fr_BE', 'Nuevo usuario en el sistema'),
(null, 'Tiene login', 'fr_BE', 'Tiene login'),
(null, 'Si', 'fr_BE', 'Si'),
(null, 'No', 'fr_BE', 'No'),
(null, 'Nuevo usuario', 'fr_BE', 'Nuevo usuario'),
(null, 'Lista de usuarios', 'fr_BE', 'Lista de usuarios'),
(null, 'Resultados de su busqueda', 'fr_BE', 'Resultados de su busqueda'),
(null, 'Ver', 'fr_BE', 'Ver'),
(null, 'Repita aca la nueva clave', 'fr_BE', 'Repita aca la nueva clave'),
(null, 'Letras, números, signos [&é#§çà, etc]', 'fr_BE', 'Letras, números, signos [&é#§çà, etc]'),
(null, 'Letras, números, signos[&é#§çà, etc]', 'fr_BE', 'Letras, números, signos[&é#§çà, etc]'),
(null, 'Su clave actual', 'fr_BE', 'Su clave actual'),
(null, 'Repita', 'fr_BE', 'Repita'),
(null, 'Nueva clave', 'fr_BE', 'Nueva clave'),
(null, 'Clave Actual', 'fr_BE', 'Clave Actual'),
(null, '123, sin ceros al inicio', 'fr_BE', '123, sin ceros al inicio'),
(null, 'Bon', 'fr_BE', 'Bon'),
(null, 'Id', 'fr_BE', 'Id'),
(null, 'Editar _grupos', 'fr_BE', 'Editar _grupos'),
(null, 'Grupos que el sistema tiene', 'fr_BE', 'Grupos que el sistema tiene'),
(null, 'Una mala manipulación puede comprometer la seguridad de su sistema', 'fr_BE', 'Una mala manipulación puede comprometer la seguridad de su sistema'),
(null, 'Si no esta seguro, no modifique nada porfavor', 'fr_BE', 'Si no esta seguro, no modifique nada porfavor'),
(null, 'ID', 'fr_BE', 'ID'),
(null, 'Editar clientes', 'fr_BE', 'Editar clientes'),
(null, 'Tva', 'fr_BE', 'Tva'),
(null, 'Login', 'fr_BE', 'Login'),
(null, 'Av. Louise 265', 'fr_BE', 'Av. Louise 265'),
(null, 'Bruxelles', 'fr_BE', 'Bruxelles'),
(null, '1000', 'fr_BE', '1000'),
(null, '123.456.789', 'fr_BE', '123.456.789'),
(null, 'info@mail.com', 'fr_BE', 'info@mail.com'),
(null, '+322123456', 'fr_BE', '+322123456'),
(null, 'Número TVA', 'fr_BE', 'Número TVA'),
(null, 'Numero TVA', 'fr_BE', 'Numero TVA'),
(null, '000.111.222', 'fr_BE', '000.111.222'),
(null, 'BE', 'fr_BE', 'BE'),
(null, 'Numero de tva', 'fr_BE', 'Numero de tva'),
(null, 'Nuevo clientes', 'fr_BE', 'Nuevo clientes'),
(null, 'Es cliente', 'fr_BE', 'Es cliente'),
(null, 'Fecha registro', 'fr_BE', 'Fecha registro'),
(null, 'Numero documento', 'fr_BE', 'Numero documento'),
(null, 'Ruc prefijo', 'fr_BE', 'Ruc prefijo'),
(null, 'Tipo documento', 'fr_BE', 'Tipo documento'),
(null, 'Lista de clientes', 'fr_BE', 'Lista de clientes'),
(null, 'Estrellas', 'fr_BE', 'Estrellas'),
(null, 'Es_cliente', 'fr_BE', 'Es_cliente'),
(null, 'Fecha_registro', 'fr_BE', 'Fecha_registro'),
(null, 'Tipo', 'fr_BE', 'Tipo'),
(null, 'Fax', 'fr_BE', 'Fax'),
(null, 'Tel', 'fr_BE', 'Tel'),
(null, 'Pais', 'fr_BE', 'Pais'),
(null, 'Provincia', 'fr_BE', 'Provincia'),
(null, 'Ciudad', 'fr_BE', 'Ciudad'),
(null, 'Cpostal', 'fr_BE', 'Cpostal'),
(null, 'Direccion', 'fr_BE', 'Direccion'),
(null, 'Saludo', 'fr_BE', 'Saludo'),
(null, 'Numero_documento', 'fr_BE', 'Numero_documento'),
(null, 'Ruc_prefijo', 'fr_BE', 'Ruc_prefijo'),
(null, 'Tipo_documento', 'fr_BE', 'Tipo_documento'),
(null, 'clientes', 'fr_BE', 'clientes'),
(null, 'txt', 'fr_BE', 'txt'),
(null, 'Editar pedidos', 'fr_BE', 'Editar pedidos'),
(null, 'email', 'fr_BE', 'email'),
(null, 'Al crear un nuevo grupo debe también configurar los permisos que este tendra en el sistema', 'fr_BE', 'Al crear un nuevo grupo debe también configurar los permisos que este tendra en el sistema'),
(null, '', 'fr_BE', ''),
(null, 'Editar _traducciones', 'fr_BE', 'Editar _traducciones'),
(null, 'Nuevo _traducciones', 'fr_BE', 'Nuevo _traducciones'),
(null, 'Registrar idioma', 'fr_BE', 'Registrar idioma'),
(null, 'xx_XX', 'fr_BE', 'xx_XX'),
(null, 'Idiomas', 'fr_BE', 'Idiomas'),
(null, 'Esta acción puede comprometar la seguridad de su web, esta seguro?', 'fr_BE', 'Esta acción puede comprometar la seguridad de su web, esta seguro?'),
(null, 'Editar _contenido', 'fr_BE', 'Editar _contenido'),
(null, 'Editar _permisos', 'fr_BE', 'Editar _permisos'),
(null, 'Nuevo _permisos', 'fr_BE', 'Nuevo _permisos'),
(null, 'Nuevo _grupos', 'fr_BE', 'Nuevo _grupos'),
(null, 'Contacte con el administrador', 'fr_BE', 'Contacte con el administrador'),
(null, 'No disponible', 'fr_BE', 'No disponible'),
(null, 'Ok', 'fr_BE', 'Ok'),
(null, 'Info', 'fr_BE', 'Info'),
(null, 'Alto', 'fr_BE', 'Alto'),
(null, 'Ayuda', 'fr_BE', 'Ayuda'),
(null, 'Atención', 'fr_BE', 'Atención'),
(null, 'cambiar_clave', 'fr_BE', 'cambiar_clave'),
(null, 'users', 'fr_BE', 'users'),
(null, 'Nuevo', 'fr_BE', 'Nuevo'),
(null, 'Nuevo _paginas', 'fr_BE', 'Nuevo _paginas'),
(null, 'Editar _paginas', 'fr_BE', 'Editar _paginas'),
(null, 'ver', 'fr_BE', 'ver'),
(null, 'Nuevo _contenido', 'fr_BE', 'Nuevo _contenido'),
(null, 'Lista de _traducciones', 'fr_BE', 'Lista de _traducciones'),
(null, 'Traduccion', 'fr_BE', 'Traduccion'),
(null, '_traducciones', 'fr_BE', '_traducciones'),
(null, 'Lista de _paginas', 'fr_BE', 'Lista de _paginas'),
(null, 'Nuevo _idiomas', 'fr_BE', 'Nuevo _idiomas'),
(null, 'Resultados de su busqueda en ', 'fr_BE', 'Resultados de su busqueda en '),
(null, 'buscar', 'fr_BE', 'buscar'),
(null, 'Enviar', 'fr_BE', 'Enviar'),
(null, 'Implante', 'fr_BE', 'Implante'),
(null, 'Codo suave', 'fr_BE', 'Codo suave'),
(null, 'Fil nylon', 'fr_BE', 'Fil nylon'),
(null, 'Pailletes', 'fr_BE', 'Pailletes'),
(null, 'Cordon', 'fr_BE', 'Cordon'),
(null, 'Hoka', 'fr_BE', 'Hoka'),
(null, 'Opciones', 'fr_BE', 'Opciones'),
(null, 'Color derecha', 'fr_BE', 'Color derecha'),
(null, 'Models', 'fr_BE', 'Models'),
(null, 'Marques', 'fr_BE', 'Marques'),
(null, 'RITE / SLIM TUBE', 'fr_BE', 'RITE / SLIM TUBE'),
(null, 'Color izquierda', 'fr_BE', 'Color izquierda'),
(null, 'Derecha', 'fr_BE', 'Derecha'),
(null, 'Ventilation Droite', 'fr_BE', 'Ventilation Droite'),
(null, 'Izquierda', 'fr_BE', 'Izquierda'),
(null, 'Ventilación', 'fr_BE', 'Ventilación'),
(null, 'Otro 2', 'fr_BE', 'Otro 2'),
(null, 'Otro 1', 'fr_BE', 'Otro 1'),
(null, 'Anti-Bactérie', 'fr_BE', 'Anti-Bactérie'),
(null, 'Thermosoft', 'fr_BE', 'Thermosoft'),
(null, 'Thermotec', 'fr_BE', 'Thermotec'),
(null, 'Silicone', 'fr_BE', 'Silicone'),
(null, 'Résine', 'fr_BE', 'Résine'),
(null, 'Materiales', 'fr_BE', 'Materiales'),
(null, 'Otro', 'fr_BE', 'Otro'),
(null, 'Iros', 'fr_BE', 'Iros'),
(null, 'Prince de Crave', 'fr_BE', 'Prince de Crave'),
(null, 'Epaulement', 'fr_BE', 'Epaulement'),
(null, 'Conduit seul', 'fr_BE', 'Conduit seul'),
(null, 'Coquille', 'fr_BE', 'Coquille'),
(null, 'Invisible', 'fr_BE', 'Invisible'),
(null, 'Modelos', 'fr_BE', 'Modelos'),
(null, 'Anti ruido', 'fr_BE', 'Anti ruido'),
(null, 'Dormir', 'fr_BE', 'Dormir'),
(null, 'Natation', 'fr_BE', 'Natation'),
(null, 'Custom Dume', 'fr_BE', 'Custom Dume'),
(null, 'Slim Tube', 'fr_BE', 'Slim Tube'),
(null, 'Rite', 'fr_BE', 'Rite'),
(null, 'Bte', 'fr_BE', 'Bte'),
(null, 'Tipos', 'fr_BE', 'Tipos'),
(null, 'Dura', 'fr_BE', 'Dura'),
(null, 'Suave', 'fr_BE', 'Suave'),
(null, 'Construcción orejera', 'fr_BE', 'Construcción orejera'),
(null, 'Grave', 'fr_BE', 'Grave'),
(null, 'Media', 'fr_BE', 'Media'),
(null, 'Ligera', 'fr_BE', 'Ligera'),
(null, 'Perdida auditiva', 'fr_BE', 'Perdida auditiva'),
(null, 'De n°', 'fr_BE', 'De n°'),
(null, 'Remake', 'fr_BE', 'Remake'),
(null, 'Payant', 'fr_BE', 'Payant'),
(null, 'Nombre del cliente', 'fr_BE', 'Nombre del cliente'),
(null, 'Centro auditivo', 'fr_BE', 'Centro auditivo'),
(null, 'Bon n°', 'fr_BE', 'Bon n°'),
(null, 'Detalles', 'fr_BE', 'Detalles'),
(null, 'Editar', 'fr_BE', 'Editar'),
(null, 'Editar _menu', 'fr_BE', 'Editar _menu'),
(null, 'editar', 'fr_BE', 'editar'),
(null, 'Nuevo _menu', 'fr_BE', 'Nuevo _menu'),
(null, 'Lista de _menu', 'fr_BE', 'Lista de _menu'),
(null, 'Orden', 'fr_BE', 'Orden'),
(null, 'Icono', 'fr_BE', 'Icono'),
(null, 'Url', 'fr_BE', 'Url'),
(null, 'Label', 'fr_BE', 'Label'),
(null, 'Padre', 'fr_BE', 'Padre'),
(null, 'Ubicacion', 'fr_BE', 'Ubicacion'),
(null, '_paginas', 'fr_BE', '_paginas'),
(null, '_menu', 'fr_BE', '_menu'),
(null, 'Lista de _permisos', 'fr_BE', 'Lista de _permisos'),
(null, 'Permiso', 'fr_BE', 'Permiso'),
(null, 'Pagina', 'fr_BE', 'Pagina'),
(null, '_permisos', 'fr_BE', '_permisos'),
(null, 'Lista de _idiomas', 'fr_BE', 'Lista de _idiomas'),
(null, 'Nombre', 'fr_BE', 'Nombre'),
(null, 'Idioma', 'fr_BE', 'Idioma'),
(null, '_idiomas', 'fr_BE', '_idiomas'),
(null, 'Nuevo _usuarios', 'fr_BE', 'Nuevo _usuarios'),
(null, 'Lista de _usuarios', 'fr_BE', 'Lista de _usuarios'),
(null, 'Clave', 'fr_BE', 'Clave'),
(null, 'Usuario', 'fr_BE', 'Usuario'),
(null, '_usuarios', 'fr_BE', '_usuarios'),
(null, 'Registrar', 'fr_BE', 'Registrar'),
(null, 'Bloqueado', 'fr_BE', 'Bloqueado'),
(null, 'Activo', 'fr_BE', 'Activo'),
(null, 'aaaa-mm-dd', 'fr_BE', 'aaaa-mm-dd'),
(null, 'Nuevo pedidos', 'fr_BE', 'Nuevo pedidos'),
(null, 'crear', 'fr_BE', 'crear'),
(null, 'Lista de pedidos', 'fr_BE', 'Lista de pedidos'),
(null, 'Estatus', 'fr_BE', 'Estatus'),
(null, 'Notas', 'fr_BE', 'Notas'),
(null, 'Fecha', 'fr_BE', 'Fecha'),
(null, 'Descripcion', 'fr_BE', 'Descripcion'),
(null, 'Email', 'fr_BE', 'Email'),
(null, 'Cliente', 'fr_BE', 'Cliente'),
(null, 'Empresa', 'fr_BE', 'Empresa'),
(null, 'Ref', 'fr_BE', 'Ref'),
(null, 'pedidos', 'fr_BE', 'pedidos'),
(null, 'Lista de _grupos', 'fr_BE', 'Lista de _grupos'),
(null, 'Grupo', 'fr_BE', 'Grupo'),
(null, '_grupos', 'fr_BE', '_grupos'),
(null, 'Accion', 'fr_BE', 'Accion'),
(null, 'Nueva', 'fr_BE', 'Nueva'),
(null, 'Lista de _contenido', 'fr_BE', 'Lista de _contenido'),
(null, 'Contexto', 'fr_BE', 'Contexto'),
(null, 'Frase', 'fr_BE', 'Frase'),
(null, 'Buscar', 'fr_BE', 'Buscar'),
(null, 'Lista', 'fr_BE', 'Lista'),
(null, '_contenido', 'fr_BE', '_contenido'),
(null, 'index', 'fr_BE', 'index'),
(null, 'home', 'fr_BE', 'home'),
(null, 'Inicio', 'fr_BE', 'Inicio'),
(null, 'Logout', 'fr_BE', 'Logout'),
(null, 'Cambiar clave', 'fr_BE', 'Cambiar clave')
;    

