UPDATE `_traducciones` SET `traduccion` = 'contenido' WHERE `_traducciones`.`id` = 13;


<hr>




<style>
    span.esconder {
    display: ;
}
</style>



<?php

$i = 1;
while ($_traducciones = mysql_fetch_array($sql)) {
   // include "./_traducciones/reg/reg.php";

    echo "<span>xxxxxxaaaa </span>"; 
    echo "<span>$_traducciones[frase]</span>"; 
    echo "<span class='esconder'> ' WHERE `_traducciones`.`id` = </span>"; 
    echo "<span>$_traducciones[id]</span>"; 
    echo ";<br>"; 
    
    
    
    
    
    // echo "(null, '$_traducciones_frase', 'fr_BE', '<font color=\"red\">$_traducciones_traduccion</font>'),<br>";
  //  echo "(null, '$_traducciones_frase', 'fr_BE', '<font color=\"red\">$_traducciones_traduccion</font>'),<br>";
    $i++;
}

?>
UPDATE `_traducciones` SET `traduccion` = 'contenido' WHERE `_traducciones`.`id` = 13;


UPDATE `_traducciones` SET `traduccion` = '' WHERE `_traducciones`.`id` = 152;
UPDATE `_traducciones` SET `traduccion` = '% Translation ' WHERE `_traducciones`.`id` = 1288;
UPDATE `_traducciones` SET `traduccion` = '+322123456 ' WHERE `_traducciones`.`id` = 185;
UPDATE `_traducciones` SET `traduccion` = '' WHERE `_traducciones`.`id` = 245;
UPDATE `_traducciones` SET `traduccion` = 'Yyyyyy 1023;
UPDATE `_traducciones` SET `traduccion` = '000,111,222 ' WHERE `_traducciones`.`id` = 182;
UPDATE `_traducciones` SET `traduccion` = '1 ' WHERE `_traducciones`.`id` = 1450;
UPDATE `_traducciones` SET `traduccion` = '1000 ' WHERE `_traducciones`.`id` = 188;
UPDATE `_traducciones` SET `traduccion` = '123, without zeros at the beginning ' WHERE `_traducciones`.`id` = 1503;
UPDATE `_traducciones` SET `traduccion` = '123, with no leading zeros ' WHERE `_traducciones`.`id` = 201;
UPDATE `_traducciones` SET `traduccion` = '123, with no leading zeros ' WHERE `_traducciones`.`id` = 1424;
UPDATE `_traducciones` SET `traduccion` = '123, with no leading zeros ' WHERE `_traducciones`.`id` = 1473;
UPDATE `_traducciones` SET `traduccion` = '123.123.123 ' WHERE `_traducciones`.`id` = 223;
UPDATE `_traducciones` SET `traduccion` = '123,456,789 ' WHERE `_traducciones`.`id` = 187;
UPDATE `_traducciones` SET `traduccion` = 'A ' WHERE `_traducciones`.`id` = 290;
UPDATE `_traducciones` SET `traduccion` = 'Action ' WHERE `_traducciones`.`id` = 20;
UPDATE `_traducciones` SET `traduccion` = 'Action ' WHERE `_traducciones`.`id` = 285;
UPDATE `_traducciones` SET `traduccion` = 'Active ' WHERE `_traducciones`.`id` = 37;
UPDATE `_traducciones` SET `traduccion` = 'Active xxxxxxaaaa, you can place orders ' WHERE `_traducciones`.`id` = 247;
UPDATE `_traducciones` SET `traduccion` = 'When creating a new group you must also configure the permissions that this will have on the system ' WHERE `_traducciones`.`id` = 153;
UPDATE `_traducciones` SET `traduccion` = 'High ' WHERE `_traducciones`.`id` = 1523;
UPDATE `_traducciones` SET `traduccion` = 'High ' WHERE `_traducciones`.`id` = 137;
UPDATE `_traducciones` SET `traduccion` = 'High ' WHERE `_traducciones`.`id` = 1524;
UPDATE `_traducciones` SET `traduccion` = 'Anti noise ' WHERE `_traducciones`.`id` = 87;
UPDATE `_traducciones` SET `traduccion` = 'Anti-Bactérie ' WHERE `_traducciones`.`id` = 101;
UPDATE `_traducciones` SET `traduccion` = 'Argument ' WHERE `_traducciones`.`id` = 292;
UPDATE `_traducciones` SET `traduccion` = 'Attention ' WHERE `_traducciones`.`id` = 135;
UPDATE `_traducciones` SET `traduccion` = 'Av. Louise 265 ' WHERE `_traducciones`.`id` = 190;
UPDATE `_traducciones` SET `traduccion` = 'Help ' WHERE `_traducciones`.`id` = 136;
UPDATE `_traducciones` SET `traduccion` = 'Help ' WHERE `_traducciones`.`id` = 1419;
UPDATE `_traducciones` SET `traduccion` = 'BE ' WHERE `_traducciones`.`id` = 181;
UPDATE `_traducciones` SET `traduccion` = 'Belgique ' WHERE `_traducciones`.`id` = 227;
UPDATE `_traducciones` SET `traduccion` = 'Locked ' WHERE `_traducciones`.`id` = 38;
UPDATE `_traducciones` SET `traduccion` = 'Locked, Can not place orders ' WHERE `_traducciones`.`id` = 248;
UPDATE `_traducciones` SET `traduccion` = 'Bon ' WHERE `_traducciones`.`id` = 200;
UPDATE `_traducciones` SET `traduccion` = 'Bon n: ' WHERE `_traducciones`.`id` = 256;
UPDATE `_traducciones` SET `traduccion` = 'Bon n ° ' WHERE `_traducciones`.`id` = 1519;
UPDATE `_traducciones` SET `traduccion` = 'Bon n ° ' WHERE `_traducciones`.`id` = 67;
UPDATE `_traducciones` SET `traduccion` = 'Bon n ° ' WHERE `_traducciones`.`id` = 1440;
UPDATE `_traducciones` SET `traduccion` = 'Bon n ° ' WHERE `_traducciones`.`id` = 1489;
UPDATE `_traducciones` SET `traduccion` = 'Bon n °: ' WHERE `_traducciones`.`id` = 1513;
UPDATE `_traducciones` SET `traduccion` = 'Bon n °: ' WHERE `_traducciones`.`id` = 257;
UPDATE `_traducciones` SET `traduccion` = 'Bon n °: ' WHERE `_traducciones`.`id` = 1434;
UPDATE `_traducciones` SET `traduccion` = 'Bon n °: ' WHERE `_traducciones`.`id` = 1483;
UPDATE `_traducciones` SET `traduccion` = 'Borar ' WHERE `_traducciones`.`id` = 1449;
UPDATE `_traducciones` SET `traduccion` = 'Deleted ' WHERE `_traducciones`.`id` = 1518;
UPDATE `_traducciones` SET `traduccion` = 'Deleted ' WHERE `_traducciones`.`id` = 264;
UPDATE `_traducciones` SET `traduccion` = 'Deleted ' WHERE `_traducciones`.`id` = 1439;
UPDATE `_traducciones` SET `traduccion` = 'Deleted ' WHERE `_traducciones`.`id` = 1488;
UPDATE `_traducciones` SET `traduccion` = 'Delete ' WHERE `_traducciones`.`id` = 262;
UPDATE `_traducciones` SET `traduccion` = 'Bruxelles ' WHERE `_traducciones`.`id` = 189;
UPDATE `_traducciones` SET `traduccion` = 'Bte ' WHERE `_traducciones`.`id` = 81;
UPDATE `_traducciones` SET `traduccion` = 'Search ' WHERE `_traducciones`.`id` = 1511;
UPDATE `_traducciones` SET `traduccion` = 'Search ' WHERE `_traducciones`.`id` = 15;
UPDATE `_traducciones` SET `traduccion` = 'Search ' WHERE `_traducciones`.`id` = 1432;
UPDATE `_traducciones` SET `traduccion` = 'Search ' WHERE `_traducciones`.`id` = 1481;
UPDATE `_traducciones` SET `traduccion` = 'Search for a customer ' WHERE `_traducciones`.`id` = 1395;
UPDATE `_traducciones` SET `traduccion` = 'Detailed search ' WHERE `_traducciones`.`id` = 1501;
UPDATE `_traducciones` SET `traduccion` = 'Detailed search ' WHERE `_traducciones`.`id` = 255;
UPDATE `_traducciones` SET `traduccion` = 'Detailed search ' WHERE `_traducciones`.`id` = 1422;
UPDATE `_traducciones` SET `traduccion` = 'Detailed search ' WHERE `_traducciones`.`id` = 1471;
UPDATE `_traducciones` SET `traduccion` = 'C ' WHERE `_traducciones`.`id` = 289;
UPDATE `_traducciones` SET `traduccion` = 'Change ' WHERE `_traducciones`.`id` = 1026;
UPDATE `_traducciones` SET `traduccion` = 'Change password ' WHERE `_traducciones`.`id` = 1495;
UPDATE `_traducciones` SET `traduccion` = 'Change password ' WHERE `_traducciones`.`id` = 8;
UPDATE `_traducciones` SET `traduccion` = 'Change password ' WHERE `_traducciones`.`id` = 1415;
UPDATE `_traducciones` SET `traduccion` = 'Change password ' WHERE `_traducciones`.`id` = 1465;
UPDATE `_traducciones` SET `traduccion` = 'Change customer ' WHERE `_traducciones`.`id` = 1021;
UPDATE `_traducciones` SET `traduccion` = 'Change password ' WHERE `_traducciones`.`id` = 1019;
UPDATE `_traducciones` SET `traduccion` = 'Change group by: ' WHERE `_traducciones`.`id` = 1392;
UPDATE `_traducciones` SET `traduccion` = 'Change the group by: ... ' WHERE `_traducciones`.`id` = 1391;
UPDATE `_traducciones` SET `traduccion` = 'Cancel ' WHERE `_traducciones`.`id` = 1020;
UPDATE `_traducciones` SET `traduccion` = 'Auditory Center ' WHERE `_traducciones`.`id` = 68;
UPDATE `_traducciones` SET `traduccion` = 'City ' WHERE `_traducciones`.`id` = 164;
UPDATE `_traducciones` SET `traduccion` = 'Password ' WHERE `_traducciones`.`id` = 42;
UPDATE `_traducciones` SET `traduccion` = 'Current Password ' WHERE `_traducciones`.`id` = 202;
UPDATE `_traducciones` SET `traduccion` = 'Incorrect current key ' WHERE `_traducciones`.`id` = 1235;
UPDATE `_traducciones` SET `traduccion` = 'New and repeat keys are not equal ' WHERE `_traducciones`.`id` = 1015;
UPDATE `_traducciones` SET `traduccion` = 'Client ' WHERE `_traducciones`.`id` = 1506;
UPDATE `_traducciones` SET `traduccion` = 'Customer ' WHERE `_traducciones`.`id` = 27;
UPDATE `_traducciones` SET `traduccion` = 'Client ' WHERE `_traducciones`.`id` = 1427;
UPDATE `_traducciones` SET `traduccion` = 'Client ' WHERE `_traducciones`.`id` = 1476;
UPDATE `_traducciones` SET `traduccion` = 'Customers ' WHERE `_traducciones`.`id` = 1393;
UPDATE `_traducciones` SET `traduccion` = 'Customers without user ' WHERE `_traducciones`.`id` = 219;
UPDATE `_traducciones` SET `traduccion` = 'Code ' WHERE `_traducciones`.`id` = 1386;
UPDATE `_traducciones` SET `traduccion` = 'Soft elbow ' WHERE `_traducciones`.`id` = 118;
UPDATE `_traducciones` SET `traduccion` = 'Right color ' WHERE `_traducciones`.`id` = 112;
UPDATE `_traducciones` SET `traduccion` = 'Color left ' WHERE `_traducciones`.`id` = 108;
UPDATE `_traducciones` SET `traduccion` = 'Available columns ' WHERE `_traducciones`.`id` = 1400;
UPDATE `_traducciones` SET `traduccion` = 'Conduit seul ' WHERE `_traducciones`.`id` = 91;
UPDATE `_traducciones` SET `traduccion` = 'Construction earplug ' WHERE `_traducciones`.`id` = 77;
UPDATE `_traducciones` SET `traduccion` = 'Contact the administrator ' WHERE `_traducciones`.`id` = 141;
UPDATE `_traducciones` SET `traduccion` = 'Content ' WHERE `_traducciones`.`id` = 1040;
UPDATE `_traducciones` SET `traduccion` = 'Context ' WHERE `_traducciones`.`id` = 17;
UPDATE `_traducciones` SET `traduccion` = 'Coquille ' WHERE `_traducciones`.`id` = 90;
UPDATE `_traducciones` SET `traduccion` = 'Cordon ' WHERE `_traducciones`.`id` = 115;
UPDATE `_traducciones` SET `traduccion` = 'Cpostal ' WHERE `_traducciones`.`id` = 163;
UPDATE `_traducciones` SET `traduccion` = 'Create ' WHERE `_traducciones`.`id` = 1448;
UPDATE `_traducciones` SET `traduccion` = 'Account blocked, can not place orders ' WHERE `_traducciones`.`id` = 246;
UPDATE `_traducciones` SET `traduccion` = 'Custom Dume ' WHERE `_traducciones`.`id` = 84;
UPDATE `_traducciones` SET `traduccion` = 'Zip code ' WHERE `_traducciones`.`id` = 226;
UPDATE `_traducciones` SET `traduccion` = 'De n ° ' WHERE `_traducciones`.`id` = 72;
UPDATE `_traducciones` SET `traduccion` = 'Demo ' WHERE `_traducciones`.`id` = 1005;
UPDATE `_traducciones` SET `traduccion` = 'Right ' WHERE `_traducciones`.`id` = 107;
UPDATE `_traducciones` SET `traduccion` = 'Description ' WHERE `_traducciones`.`id` = 29;
UPDATE `_traducciones` SET `traduccion` = 'Details ' WHERE `_traducciones`.`id` = 66;
UPDATE `_traducciones` SET `traduccion` = 'Order Details ' WHERE `_traducciones`.`id` = 1006;
UPDATE `_traducciones` SET `traduccion` = 'Address ' WHERE `_traducciones`.`id` = 162;
UPDATE `_traducciones` SET `traduccion` = '' WHERE `_traducciones`.`id` = address 229;
UPDATE `_traducciones` SET `traduccion` = 'Sleeping ' WHERE `_traducciones`.`id` = 86;
UPDATE `_traducciones` SET `traduccion` = 'Dura ' WHERE `_traducciones`.`id` = 79;
UPDATE `_traducciones` SET `traduccion` = 'Edit ' WHERE `_traducciones`.`id` = 1521;
UPDATE `_traducciones` SET `traduccion` = 'Edit ' WHERE `_traducciones`.`id` = 65;
UPDATE `_traducciones` SET `traduccion` = 'Edit ' WHERE `_traducciones`.`id` = 1443;
UPDATE `_traducciones` SET `traduccion` = 'Edit ' WHERE `_traducciones`.`id` = 1491;
UPDATE `_traducciones` SET `traduccion` = 'Edit _content ' WHERE `_traducciones`.`id` = 145;
UPDATE `_traducciones` SET `traduccion` = 'Edit _groups ' WHERE `_traducciones`.`id` = 198;
UPDATE `_traducciones` SET `traduccion` = 'Edit _idiomas ' WHERE `_traducciones`.`id` = 1017;
UPDATE `_traducciones` SET `traduccion` = 'Edit _menu ' WHERE `_traducciones`.`id` = 64;
UPDATE `_traducciones` SET `traduccion` = 'Edit _paginas ' WHERE `_traducciones`.`id` = 130;
UPDATE `_traducciones` SET `traduccion` = 'Edit _permisos ' WHERE `_traducciones`.`id` = 144;
UPDATE `_traducciones` SET `traduccion` = 'Edit _translations ' WHERE `_traducciones`.`id` = 151;
UPDATE `_traducciones` SET `traduccion` = 'Edit _users ' WHERE `_traducciones`.`id` = 239;
UPDATE `_traducciones` SET `traduccion` = 'Edit clients ' WHERE `_traducciones`.`id` = 193;
UPDATE `_traducciones` SET `traduccion` = 'Edit logs ' WHERE `_traducciones`.`id` = 1444;
UPDATE `_traducciones` SET `traduccion` = 'Edit orders ' WHERE `_traducciones`.`id` = 155;
UPDATE `_traducciones` SET `traduccion` = 'Run ' WHERE `_traducciones`.`id` = 1388;
UPDATE `_traducciones` SET `traduccion` = 'Content is automatically generated, you can not add ' WHERE `_traducciones`.`id` = 1411;
UPDATE `_traducciones` SET `traduccion` = 'The order is being processed ' WHERE `_traducciones`.`id` = 267;
UPDATE `_traducciones` SET `traduccion` = 'The order is being processed, can not edit it ' WHERE `_traducciones`.`id` = 268;
UPDATE `_traducciones` SET `traduccion` = 'Email ' WHERE `_traducciones`.`id` = 1507;
UPDATE `_traducciones` SET `traduccion` = 'Email ' WHERE `_traducciones`.`id` = 28;
UPDATE `_traducciones` SET `traduccion` = 'Email ' WHERE `_traducciones`.`id` = 1428;
UPDATE `_traducciones` SET `traduccion` = 'Email ' WHERE `_traducciones`.`id` = 1477;
UPDATE `_traducciones` SET `traduccion` = 'Email already exists in the database ' WHERE `_traducciones`.`id` = 237;
UPDATE `_traducciones` SET `traduccion` = 'Company ' WHERE `_traducciones`.`id` = 1505;
UPDATE `_traducciones` SET `traduccion` = 'Company ' WHERE `_traducciones`.`id` = 26;
UPDATE `_traducciones` SET `traduccion` = 'Company ' WHERE `_traducciones`.`id` = 1426;
UPDATE `_traducciones` SET `traduccion` = 'Company ' WHERE `_traducciones`.`id` = 1475;
UPDATE `_traducciones` SET `traduccion` = 'Company SPRL ' WHERE `_traducciones`.`id` = 228;
UPDATE `_traducciones` SET `traduccion` = 'In process ' WHERE `_traducciones`.`id` = 1516;
UPDATE `_traducciones` SET `traduccion` = 'In process ' WHERE `_traducciones`.`id` = 260;
UPDATE `_traducciones` SET `traduccion` = 'In process ' WHERE `_traducciones`.`id` = 1437;
UPDATE `_traducciones` SET `traduccion` = 'In process ' WHERE `_traducciones`.`id` = 1486;
UPDATE `_traducciones` SET `traduccion` = 'Sent ' WHERE `_traducciones`.`id` = 1517;
UPDATE `_traducciones` SET `traduccion` = 'Sent ' WHERE `_traducciones`.`id` = 263;
UPDATE `_traducciones` SET `traduccion` = 'Sent ' WHERE `_traducciones`.`id` = 1438;
UPDATE `_traducciones` SET `traduccion` = 'Sent ' WHERE `_traducciones`.`id` = 1487;
UPDATE `_traducciones` SET `traduccion` = 'Sent to client ' WHERE `_traducciones`.`id` = 261;
UPDATE `_traducciones` SET `traduccion` = 'Send ' WHERE `_traducciones`.`id` = 120;
UPDATE `_traducciones` SET `traduccion` = 'Epaulement ' WHERE `_traducciones`.`id` = 92;
UPDATE `_traducciones` SET `traduccion` = 'Error ' WHERE `_traducciones`.`id` = 1241;
UPDATE `_traducciones` SET `traduccion` = 'Error License ' WHERE `_traducciones`.`id` = 1460;
UPDATE `_traducciones` SET `traduccion` = 'You are a ' WHERE `_traducciones`.`id` = customer 178;
UPDATE `_traducciones` SET `traduccion` = 'Es_cliente ' WHERE `_traducciones`.`id` = 171;
UPDATE `_traducciones` SET `traduccion` = 'This action may compromise the security of your website, are you sure? Yyyyyy 146;
UPDATE `_traducciones` SET `traduccion` = 'Status ' WHERE `_traducciones`.`id` = 1510;
UPDATE `_traducciones` SET `traduccion` = 'Status ' WHERE `_traducciones`.`id` = 32;
UPDATE `_traducciones` SET `traduccion` = 'Status ' WHERE `_traducciones`.`id` = 1431;
UPDATE `_traducciones` SET `traduccion` = 'Status ' WHERE `_traducciones`.`id` = 1480;
UPDATE `_traducciones` SET `traduccion` = 'Status of orderDeleted ' WHERE `_traducciones`.`id` = 270;
UPDATE `_traducciones` SET `traduccion` = 'This request does not belong to you ' WHERE `_traducciones`.`id` = 232;
UPDATE `_traducciones` SET `traduccion` = 'Stars ' WHERE `_traducciones`.`id` = 172;
UPDATE `_traducciones` SET `traduccion` = 'Fax ' WHERE `_traducciones`.`id` = 168;
UPDATE `_traducciones` SET `traduccion` = 'Date ' WHERE `_traducciones`.`id` = 1508;
UPDATE `_traducciones` SET `traduccion` = 'Date ' WHERE `_traducciones`.`id` = 30;
UPDATE `_traducciones` SET `traduccion` = 'Date ' WHERE `_traducciones`.`id` = 1429;
UPDATE `_traducciones` SET `traduccion` = 'Date ' WHERE `_traducciones`.`id` = 1478;
UPDATE `_traducciones` SET `traduccion` = 'Registration date ' WHERE `_traducciones`.`id` = 177;
UPDATE `_traducciones` SET `traduccion` = 'RecordDate ' WHERE `_traducciones`.`id` = 170;
UPDATE `_traducciones` SET `traduccion` = 'Fil nylon ' WHERE `_traducciones`.`id` = 117;
UPDATE `_traducciones` SET `traduccion` = 'Text format ' WHERE `_traducciones`.`id` = 258;
UPDATE `_traducciones` SET `traduccion` = 'Sentence ' WHERE `_traducciones`.`id` = 16;
UPDATE `_traducciones` SET `traduccion` = 'Grave ' WHERE `_traducciones`.`id` = 76;
UPDATE `_traducciones` SET `traduccion` = 'Group ' WHERE `_traducciones`.`id` = 22;
UPDATE `_traducciones` SET `traduccion` = 'Groups that the system has ' WHERE `_traducciones`.`id` = 197;
UPDATE `_traducciones` SET `traduccion` = 'There is a new version, here to update your system ' WHERE `_traducciones`.`id` = 1383;
UPDATE `_traducciones` SET `traduccion` = 'There is a new version, here to update your system ' WHERE `_traducciones`.`id` = 1384;
UPDATE `_traducciones` SET `traduccion` = 'There is a new version, click here to update your system ' WHERE `_traducciones`.`id` = 1382;
UPDATE `_traducciones` SET `traduccion` = 'Hoka ' WHERE `_traducciones`.`id` = 114;
UPDATE `_traducciones` SET `traduccion` = 'Hi ' WHERE `_traducciones`.`id` = 1007;
UPDATE `_traducciones` SET `traduccion` = 'ID ' WHERE `_traducciones`.`id` = 194;
UPDATE `_traducciones` SET `traduccion` = 'Icon ' WHERE `_traducciones`.`id` = 59;
UPDATE `_traducciones` SET `traduccion` = 'Id ' WHERE `_traducciones`.`id` = 1502;
UPDATE `_traducciones` SET `traduccion` = 'Id ' WHERE `_traducciones`.`id` = 199;
UPDATE `_traducciones` SET `traduccion` = 'Id ' WHERE `_traducciones`.`id` = 1423;
UPDATE `_traducciones` SET `traduccion` = 'Id ' WHERE `_traducciones`.`id` = 1472;
UPDATE `_traducciones` SET `traduccion` = 'OrderID ' WHERE `_traducciones`.`id` = 294;
UPDATE `_traducciones` SET `traduccion` = 'Language ' WHERE `_traducciones`.`id` = 46;
UPDATE `_traducciones` SET `traduccion` = 'Languages ​​' WHERE `_traducciones`.`id` = 1494;
UPDATE `_traducciones` SET `traduccion` = 'Languages ​​' WHERE `_traducciones`.`id` = 147;
UPDATE `_traducciones` SET `traduccion` = 'Languages ​​' WHERE `_traducciones`.`id` = 1414;
UPDATE `_traducciones` SET `traduccion` = 'Languages ​​' WHERE `_traducciones`.`id` = 1464;
UPDATE `_traducciones` SET `traduccion` = 'Implant ' WHERE `_traducciones`.`id` = 119;
UPDATE `_traducciones` SET `traduccion` = 'Info ' WHERE `_traducciones`.`id` = 138;
UPDATE `_traducciones` SET `traduccion` = 'Home ' WHERE `_traducciones`.`id` = 1493;
UPDATE `_traducciones` SET `traduccion` = 'Home ' WHERE `_traducciones`.`id` = 10;
UPDATE `_traducciones` SET `traduccion` = 'Home ' WHERE `_traducciones`.`id` = 1412;
UPDATE `_traducciones` SET `traduccion` = 'Home ' WHERE `_traducciones`.`id` = 1463;
UPDATE `_traducciones` SET `traduccion` = 'Invisible ' WHERE `_traducciones`.`id` = 89;
UPDATE `_traducciones` SET `traduccion` = 'Iros ' WHERE `_traducciones`.`id` = 94;
UPDATE `_traducciones` SET `traduccion` = 'Items ' WHERE `_traducciones`.`id` = 1009;
UPDATE `_traducciones` SET `traduccion` = 'Left ' WHERE `_traducciones`.`id` = 105;
UPDATE `_traducciones` SET `traduccion` = 'Label ' WHERE `_traducciones`.`id` = 57;
UPDATE `_traducciones` SET `traduccion` = 'Letters, numbers, signs [& é # §çà, etc] ' WHERE `_traducciones`.`id` = 207;
UPDATE `_traducciones` SET `traduccion` = 'Letters, numbers, signs [& é # §çà, etc] ' WHERE `_traducciones`.`id` = 1455;
UPDATE `_traducciones` SET `traduccion` = 'Letters, numbers, signs [& é # §çà, etc] ' WHERE `_traducciones`.`id` = 206;
UPDATE `_traducciones` SET `traduccion` = 'Ligera ' WHERE `_traducciones`.`id` = 74;
UPDATE `_traducciones` SET `traduccion` = 'List ' WHERE `_traducciones`.`id` = 1500;
UPDATE `_traducciones` SET `traduccion` = 'List ' WHERE `_traducciones`.`id` = 14;
UPDATE `_traducciones` SET `traduccion` = 'List ' WHERE `_traducciones`.`id` = 1421;
UPDATE `_traducciones` SET `traduccion` = 'List ' WHERE `_traducciones`.`id` = 1470;
UPDATE `_traducciones` SET `traduccion` = 'List of _contenido ' WHERE `_traducciones`.`id` = 18;
UPDATE `_traducciones` SET `traduccion` = 'List of _groups ' WHERE `_traducciones`.`id` = 23;
UPDATE `_traducciones` SET `traduccion` = 'List of _idiomas ' WHERE `_traducciones`.`id` = 48;
UPDATE `_traducciones` SET `traduccion` = 'List of _menu ' WHERE `_traducciones`.`id` = 61;
UPDATE `_traducciones` SET `traduccion` = 'List of pages ' WHERE `_traducciones`.`id` = 124;
UPDATE `_traducciones` SET `traduccion` = 'List of _permisos ' WHERE `_traducciones`.`id` = 52;
UPDATE `_traducciones` SET `traduccion` = 'List of _translations ' WHERE `_traducciones`.`id` = 127;
UPDATE `_traducciones` SET `traduccion` = 'List of _users ' WHERE `_traducciones`.`id` = 43;
UPDATE `_traducciones` SET `traduccion` = 'List of updates ' WHERE `_traducciones`.`id` = 1389;
UPDATE `_traducciones` SET `traduccion` = 'List of customers ' WHERE `_traducciones`.`id` = 173;
UPDATE `_traducciones` SET `traduccion` = 'List of logs ' WHERE `_traducciones`.`id` = 295;
UPDATE `_traducciones` SET `traduccion` = 'Wishlist ' WHERE `_traducciones`.`id` = 33;
UPDATE `_traducciones` SET `traduccion` = 'User list ' WHERE `_traducciones`.`id` = 211;
UPDATE `_traducciones` SET `traduccion` = 'Login ' WHERE `_traducciones`.`id` = 191;
UPDATE `_traducciones` SET `traduccion` = 'Logout ' WHERE `_traducciones`.`id` = 1496;
UPDATE `_traducciones` SET `traduccion` = 'Logout ' WHERE `_traducciones`.`id` = 9;
UPDATE `_traducciones` SET `traduccion` = 'Logout ' WHERE `_traducciones`.`id` = 1416;
UPDATE `_traducciones` SET `traduccion` = 'Logout ' WHERE `_traducciones`.`id` = 1466;
UPDATE `_traducciones` SET `traduccion` = 'Logs, can not edit ' WHERE `_traducciones`.`id` = 1445;
UPDATE `_traducciones` SET `traduccion` = 'Marques ' WHERE `_traducciones`.`id` = 110;
UPDATE `_traducciones` SET `traduccion` = 'Materials ' WHERE `_traducciones`.`id` = 96;
UPDATE `_traducciones` SET `traduccion` = 'Media ' WHERE `_traducciones`.`id` = 75;
UPDATE `_traducciones` SET `traduccion` = 'My orders ' WHERE `_traducciones`.`id` = 271;
UPDATE `_traducciones` SET `traduccion` = 'Mix ' WHERE `_traducciones`.`id` = 252;
UPDATE `_traducciones` SET `traduccion` = 'Models ' WHERE `_traducciones`.`id` = 88;
UPDATE `_traducciones` SET `traduccion` = 'Models ' WHERE `_traducciones`.`id` = 111;
UPDATE `_traducciones` SET `traduccion` = 'Natation ' WHERE `_traducciones`.`id` = 85;
UPDATE `_traducciones` SET `traduccion` = 'No ' WHERE `_traducciones`.`id` = 213;
UPDATE `_traducciones` SET `traduccion` = 'Not available ' WHERE `_traducciones`.`id` = 140;
UPDATE `_traducciones` SET `traduccion` = 'Unable to add root users ' WHERE `_traducciones`.`id` = 241;
UPDATE `_traducciones` SET `traduccion` = 'You do not have permission to edit orders that do not belong to you ' WHERE `_traducciones`.`id` = 1373;
UPDATE `_traducciones` SET `traduccion` = 'No, create one ' WHERE `_traducciones`.`id` = 221;
UPDATE `_traducciones` SET `traduccion` = 'No, create one. Yyyyyy 233;
UPDATE `_traducciones` SET `traduccion` = 'Name ' WHERE `_traducciones`.`id` = 47;
UPDATE `_traducciones` SET `traduccion` = 'Customer name ' WHERE `_traducciones`.`id` = 69;
UPDATE `_traducciones` SET `traduccion` = 'First and Last Names ' WHERE `_traducciones`.`id` = 224;
UPDATE `_traducciones` SET `traduccion` = 'Notes ' WHERE `_traducciones`.`id` = 1509;
UPDATE `_traducciones` SET `traduccion` = 'Notes ' WHERE `_traducciones`.`id` = 31;
UPDATE `_traducciones` SET `traduccion` = 'Notes ' WHERE `_traducciones`.`id` = 1430;
UPDATE `_traducciones` SET `traduccion` = 'Notes ' WHERE `_traducciones`.`id` = 1479;
UPDATE `_traducciones` SET `traduccion` = 'New ' WHERE `_traducciones`.`id` = 19;
UPDATE `_traducciones` SET `traduccion` = 'New Password ' WHERE `_traducciones`.`id` = 1027;
UPDATE `_traducciones` SET `traduccion` = 'New password ' WHERE `_traducciones`.`id` = 203;
UPDATE `_traducciones` SET `traduccion` = 'New key ' WHERE `_traducciones`.`id` = 1454;
UPDATE `_traducciones` SET `traduccion` = 'Nuevo ' WHERE `_traducciones`.`id` = 1512;
UPDATE `_traducciones` SET `traduccion` = 'Nuevo ' WHERE `_traducciones`.`id` = 132;
UPDATE `_traducciones` SET `traduccion` = 'Nuevo ' WHERE `_traducciones`.`id` = 1433;
UPDATE `_traducciones` SET `traduccion` = 'Nuevo ' WHERE `_traducciones`.`id` = 1482;
UPDATE `_traducciones` SET `traduccion` = 'New _content ' WHERE `_traducciones`.`id` = 128;
UPDATE `_traducciones` SET `traduccion` = 'New _' WHERE `_traducciones`.`id` = 142 groups;
UPDATE `_traducciones` SET `traduccion` = 'Nuevo _idiomas ' WHERE `_traducciones`.`id` = 123;
UPDATE `_traducciones` SET `traduccion` = 'New _menu ' WHERE `_traducciones`.`id` = 62;
UPDATE `_traducciones` SET `traduccion` = 'New _paginas ' WHERE `_traducciones`.`id` = 131;
UPDATE `_traducciones` SET `traduccion` = 'New _permisos ' WHERE `_traducciones`.`id` = 143;
UPDATE `_traducciones` SET `traduccion` = 'New _translations ' WHERE `_traducciones`.`id` = 150;
UPDATE `_traducciones` SET `traduccion` = 'New _users ' WHERE `_traducciones`.`id` = 44;
UPDATE `_traducciones` SET `traduccion` = 'New updates ' WHERE `_traducciones`.`id` = 1447;
UPDATE `_traducciones` SET `traduccion` = 'New client ' WHERE `_traducciones`.`id` = 231;
UPDATE `_traducciones` SET `traduccion` = 'New customers ' WHERE `_traducciones`.`id` = 179;
UPDATE `_traducciones` SET `traduccion` = 'New logs ' WHERE `_traducciones`.`id` = 287;
UPDATE `_traducciones` SET `traduccion` = 'New order via web ' WHERE `_traducciones`.`id` = 312;
UPDATE `_traducciones` SET `traduccion` = 'New orders ' WHERE `_traducciones`.`id` = 35;
UPDATE `_traducciones` SET `traduccion` = 'New user ' WHERE `_traducciones`.`id` = 212;
UPDATE `_traducciones` SET `traduccion` = 'New user on ' WHERE `_traducciones`.`id` = 216 system;
UPDATE `_traducciones` SET `traduccion` = 'Number TVA ' WHERE `_traducciones`.`id` = 183;
UPDATE `_traducciones` SET `traduccion` = 'Number of tva ' WHERE `_traducciones`.`id` = 180;
UPDATE `_traducciones` SET `traduccion` = 'Document number ' WHERE `_traducciones`.`id` = 176;
UPDATE `_traducciones` SET `traduccion` = 'Document_number ' WHERE `_traducciones`.`id` = 160;
UPDATE `_traducciones` SET `traduccion` = 'TVA number ' WHERE `_traducciones`.`id` = 184;
UPDATE `_traducciones` SET `traduccion` = 'Number does not exist ' WHERE `_traducciones`.`id` = 254;
UPDATE `_traducciones` SET `traduccion` = 'Ok ' WHERE `_traducciones`.`id` = 139;
UPDATE `_traducciones` SET `traduccion` = 'I forget the email ' WHERE `_traducciones`.`id` = 240;
UPDATE `_traducciones` SET `traduccion` = 'I forget the order number ' WHERE `_traducciones`.`id` = 1405;
UPDATE `_traducciones` SET `traduccion` = 'I forget email ' WHERE `_traducciones`.`id` = 238;
UPDATE `_traducciones` SET `traduccion` = 'I forget your current password ' WHERE `_traducciones`.`id` = 1016;
UPDATE `_traducciones` SET `traduccion` = 'Options ' WHERE `_traducciones`.`id` = 113;
UPDATE `_traducciones` SET `traduccion` = 'Order ' WHERE `_traducciones`.`id` = 60;
UPDATE `_traducciones` SET `traduccion` = 'Other ' WHERE `_traducciones`.`id` = 95;
UPDATE `_traducciones` SET `traduccion` = 'Other 1 ' WHERE `_traducciones`.`id` = 102;
UPDATE `_traducciones` SET `traduccion` = 'Other 2 ' WHERE `_traducciones`.`id` = 103;
UPDATE `_traducciones` SET `traduccion` = 'P ' WHERE `_traducciones`.`id` = 288;
UPDATE `_traducciones` SET `traduccion` = 'Father ' WHERE `_traducciones`.`id` = 56;
UPDATE `_traducciones` SET `traduccion` = 'Page ' WHERE `_traducciones`.`id` = 50;
UPDATE `_traducciones` SET `traduccion` = 'Patios ' WHERE `_traducciones`.`id` = 116;
UPDATE `_traducciones` SET `traduccion` = 'Country ' WHERE `_traducciones`.`id` = 166;
UPDATE `_traducciones` SET `traduccion` = 'For a user to have a login, he must first be registered in the client list ' WHERE `_traducciones`.`id` = 218;
UPDATE `_traducciones` SET `traduccion` = 'For a user to have a login, must be registered first in the list of customers, if the client already has a login will not appear in this list ' WHERE `_traducciones`.`id` = 220;
UPDATE `_traducciones` SET `traduccion` = 'For a user to have a login, he must first be registered in the client list ' WHERE `_traducciones`.`id` = 217;
UPDATE `_traducciones` SET `traduccion` = 'Payant ' WHERE `_traducciones`.`id` = 70;
UPDATE `_traducciones` SET `traduccion` = 'Country ' WHERE `_traducciones`.`id` = 230;
UPDATE `_traducciones` SET `traduccion` = 'Request ' WHERE `_traducciones`.`id` = 291;
UPDATE `_traducciones` SET `traduccion` = 'Order does not exist or can not be edited ' WHERE `_traducciones`.`id` = 1371;
UPDATE `_traducciones` SET `traduccion` = 'Order does not belong to you ' WHERE `_traducciones`.`id` = 249;
UPDATE `_traducciones` SET `traduccion` = 'Order does not belong to you, or you do not have permission to edit it ' WHERE `_traducciones`.`id` = 1372;
UPDATE `_traducciones` SET `traduccion` = 'Request can not be edited ' WHERE `_traducciones`.`id` = 1404;
UPDATE `_traducciones` SET `traduccion` = 'Orders ' WHERE `_traducciones`.`id` = 1499;
UPDATE `_traducciones` SET `traduccion` = 'Requests ' WHERE `_traducciones`.`id` = 234;
UPDATE `_traducciones` SET `traduccion` = 'Orders ' WHERE `_traducciones`.`id` = 1413;
UPDATE `_traducciones` SET `traduccion` = 'Orders ' WHERE `_traducciones`.`id` = 1469;
UPDATE `_traducciones` SET `traduccion` = 'Orders Edit ' WHERE `_traducciones`.`id` = 253;
UPDATE `_traducciones` SET `traduccion` = 'Hearing loss ' WHERE `_traducciones`.`id` = 73;
UPDATE `_traducciones` SET `traduccion` = 'Permission ' WHERE `_traducciones`.`id` = 51;
UPDATE `_traducciones` SET `traduccion` = 'By default the centers group will be assigned to any new user ' WHERE `_traducciones`.`id` = 244;
UPDATE `_traducciones` SET `traduccion` = 'Prince de Crave ' WHERE `_traducciones`.`id` = 93;
UPDATE `_traducciones` SET `traduccion` = 'Province ' WHERE `_traducciones`.`id` = 165;
UPDATE `_traducciones` SET `traduccion` = 'Page ' WHERE `_traducciones`.`id` = 284;
UPDATE `_traducciones` SET `traduccion` = 'Pages ' WHERE `_traducciones`.`id` = 1402;
UPDATE `_traducciones` SET `traduccion` = 'RITE / SLIM TUBE ' WHERE `_traducciones`.`id` = 109;
UPDATE `_traducciones` SET `traduccion` = 'Ref ' WHERE `_traducciones`.`id` = 1504;
UPDATE `_traducciones` SET `traduccion` = 'Ref ' WHERE `_traducciones`.`id` = 25;
UPDATE `_traducciones` SET `traduccion` = 'Ref ' WHERE `_traducciones`.`id` = 1425;
UPDATE `_traducciones` SET `traduccion` = 'Ref ' WHERE `_traducciones`.`id` = 1474;
UPDATE `_traducciones` SET `traduccion` = 'Registered ' WHERE `_traducciones`.`id` = 1515;
UPDATE `_traducciones` SET `traduccion` = 'Registered ' WHERE `_traducciones`.`id` = 259;
UPDATE `_traducciones` SET `traduccion` = 'Registered ' WHERE `_traducciones`.`id` = 1436;
UPDATE `_traducciones` SET `traduccion` = 'Registered ' WHERE `_traducciones`.`id` = 1485;
UPDATE `_traducciones` SET `traduccion` = 'Register ' WHERE `_traducciones`.`id` = 39;
UPDATE `_traducciones` SET `traduccion` = 'Register ' WHERE `_traducciones`.`id` = 1459;
UPDATE `_traducciones` SET `traduccion` = 'Register language ' WHERE `_traducciones`.`id` = 149;
UPDATE `_traducciones` SET `traduccion` = 'Remake ' WHERE `_traducciones`.`id` = 71;
UPDATE `_traducciones` SET `traduccion` = 'Repeat ' WHERE `_traducciones`.`id` = 204;
UPDATE `_traducciones` SET `traduccion` = 'Repeat ' WHERE `_traducciones`.`id` = 1456;
UPDATE `_traducciones` SET `traduccion` = 'Repeat here the new key ' WHERE `_traducciones`.`id` = 208;
UPDATE `_traducciones` SET `traduccion` = 'Repeat here the new key ' WHERE `_traducciones`.`id` = 1457;
UPDATE `_traducciones` SET `traduccion` = 'Requires ' WHERE `_traducciones`.`id` = 1387;
UPDATE `_traducciones` SET `traduccion` = 'Your search results ' WHERE `_traducciones`.`id` = 210;
UPDATE `_traducciones` SET `traduccion` = 'Results of your search on ' WHERE `_traducciones`.`id` = 122;
UPDATE `_traducciones` SET `traduccion` = 'Rite ' WHERE `_traducciones`.`id` = 82;
UPDATE `_traducciones` SET `traduccion` = 'Ruc prefix ' WHERE `_traducciones`.`id` = 175;
UPDATE `_traducciones` SET `traduccion` = 'Ruc_prefix ' WHERE `_traducciones`.`id` = 159;
UPDATE `_traducciones` SET `traduccion` = 'Résine ' WHERE `_traducciones`.`id` = 97;
UPDATE `_traducciones` SET `traduccion` = 'Greeting ' WHERE `_traducciones`.`id` = 161;
UPDATE `_traducciones` SET `traduccion` = 'Si ' WHERE `_traducciones`.`id` = 214;
UPDATE `_traducciones` SET `traduccion` = 'If you are not sure, do not modify anything please ' WHERE `_traducciones`.`id` = 195;
UPDATE `_traducciones` SET `traduccion` = 'If a customer already has registered orders, you can not change e-mail and ' WHERE `_traducciones`.`id` = 235;
UPDATE `_traducciones` SET `traduccion` = 'Silicone ' WHERE `_traducciones`.`id` = 98;
UPDATE `_traducciones` SET `traduccion` = 'Slim Tube ' WHERE `_traducciones`.`id` = 83;
UPDATE `_traducciones` SET `traduccion` = 'Mr. Mrs. Miss Dr. Dr. ... ' WHERE `_traducciones`.`id` = 225;
UPDATE `_traducciones` SET `traduccion` = 'Your current password ' WHERE `_traducciones`.`id` = 205;
UPDATE `_traducciones` SET `traduccion` = 'Suave ' WHERE `_traducciones`.`id` = 78;
UPDATE `_traducciones` SET `traduccion` = 'System code is incorrect ' WHERE `_traducciones`.`id` = 1461;
UPDATE `_traducciones` SET `traduccion` = 'System code is incorrect (License error) ' WHERE `_traducciones`.`id` = 1462;
UPDATE `_traducciones` SET `traduccion` = 'TVA ' WHERE `_traducciones`.`id` = 222;
UPDATE `_traducciones` SET `traduccion` = 'Tel ' WHERE `_traducciones`.`id` = 167;
UPDATE `_traducciones` SET `traduccion` = 'Thermosoft ' WHERE `_traducciones`.`id` = 100;
UPDATE `_traducciones` SET `traduccion` = 'Thermotec ' WHERE `_traducciones`.`id` = 99;
UPDATE `_traducciones` SET `traduccion` = 'You have login ' WHERE `_traducciones`.`id` = 215;
UPDATE `_traducciones` SET `traduccion` = 'Type ' WHERE `_traducciones`.`id` = 169;
UPDATE `_traducciones` SET `traduccion` = 'Type document ' WHERE `_traducciones`.`id` = 174;
UPDATE `_traducciones` SET `traduccion` = 'Document Type ' WHERE `_traducciones`.`id` = 158;
UPDATE `_traducciones` SET `traduccion` = 'Types ' WHERE `_traducciones`.`id` = 80;
UPDATE `_traducciones` SET `traduccion` = 'All ' WHERE `_traducciones`.`id` = 1514;
UPDATE `_traducciones` SET `traduccion` = 'All ' WHERE `_traducciones`.`id` = 286;
UPDATE `_traducciones` SET `traduccion` = 'All ' WHERE `_traducciones`.`id` = 1435;
UPDATE `_traducciones` SET `traduccion` = 'All ' WHERE `_traducciones`.`id` = 1484;
UPDATE `_traducciones` SET `traduccion` = 'Translation ' WHERE `_traducciones`.`id` = 126;
UPDATE `_traducciones` SET `traduccion` = 'Translation ' WHERE `_traducciones`.`id` = 1038;
UPDATE `_traducciones` SET `traduccion` = 'Translated andyyyyy 1287;
UPDATE `_traducciones` SET `traduccion` = 'Tva ' WHERE `_traducciones`.`id` = 192;
UPDATE `_traducciones` SET `traduccion` = 'Location ' WHERE `_traducciones`.`id` = 55;
UPDATE `_traducciones` SET `traduccion` = 'Location ' WHERE `_traducciones`.`id` = 1410;
UPDATE `_traducciones` SET `traduccion` = 'A new order is to be registered in the system ' WHERE `_traducciones`.`id` = 1008;
UPDATE `_traducciones` SET `traduccion` = 'Bad handling can compromise the security of your system ' WHERE `_traducciones`.`id` = 196;
UPDATE `_traducciones` SET `traduccion` = 'Once the key changed, you will have to reconnect with the new key. Yyyyyy 1031;
UPDATE `_traducciones` SET `traduccion` = 'Once the key changed, you will have to reconnect with the new key. Yyyyyy 1458;
UPDATE `_traducciones` SET `traduccion` = 'Url ' WHERE `_traducciones`.`id` = 58;
UPDATE `_traducciones` SET `traduccion` = 'Used to login ' WHERE `_traducciones`.`id` = 1401;
UPDATE `_traducciones` SET `traduccion` = 'User ' WHERE `_traducciones`.`id` = 41;
UPDATE `_traducciones` SET `traduccion` = 'User ' WHERE `_traducciones`.`id` = 1453;
UPDATE `_traducciones` SET `traduccion` = 'Users ' WHERE `_traducciones`.`id` = 243;
UPDATE `_traducciones` SET `traduccion` = 'Value ' WHERE `_traducciones`.`id` = 1010;
UPDATE `_traducciones` SET `traduccion` = 'Ventilation ' WHERE `_traducciones`.`id` = 104;
UPDATE `_traducciones` SET `traduccion` = 'Ventilation Droite ' WHERE `_traducciones`.`id` = 106;
UPDATE `_traducciones` SET `traduccion` = 'See ' WHERE `_traducciones`.`id` = 1520;
UPDATE `_traducciones` SET `traduccion` = 'See ' WHERE `_traducciones`.`id` = 209;
UPDATE `_traducciones` SET `traduccion` = 'See ' WHERE `_traducciones`.`id` = 1442;
UPDATE `_traducciones` SET `traduccion` = 'See ' WHERE `_traducciones`.`id` = 1490;
UPDATE `_traducciones` SET `traduccion` = 'You can no longer edit this request ' WHERE `_traducciones`.`id` = 269;
UPDATE `_traducciones` SET `traduccion` = '_content ' WHERE `_traducciones`.`id` = 13;
UPDATE `_traducciones` SET `traduccion` = '_groups ' WHERE `_traducciones`.`id` = 21;
UPDATE `_traducciones` SET `traduccion` = '_idiomas ' WHERE `_traducciones`.`id` = 45;
UPDATE `_traducciones` SET `traduccion` = '_menu ' WHERE `_traducciones`.`id` = 53;
UPDATE `_traducciones` SET `traduccion` = '_paginas ' WHERE `_traducciones`.`id` = 54;
UPDATE `_traducciones` SET `traduccion` = '_permisos ' WHERE `_traducciones`.`id` = 49;
UPDATE `_traducciones` SET `traduccion` = '_translations ' WHERE `_traducciones`.`id` = 125;
UPDATE `_traducciones` SET `traduccion` = '_users ' WHERE `_traducciones`.`id` = 40;
UPDATE `_traducciones` SET `traduccion` = '_users ' WHERE `_traducciones`.`id` = 1451;
UPDATE `_traducciones` SET `traduccion` = 'a ' WHERE `_traducciones`.`id` = 298;
UPDATE `_traducciones` SET `traduccion` = 'aa ' WHERE `_traducciones`.`id` = 1032;
UPDATE `_traducciones` SET `traduccion` = 'aaaa-mm-dd ' WHERE `_traducciones`.`id` = 36;
UPDATE `_traducciones` SET `traduccion` = 'action ' WHERE `_traducciones`.`id` = 1399;
UPDATE `_traducciones` SET `traduccion` = 'updates ' WHERE `_traducciones`.`id` = 1385;
UPDATE `_traducciones` SET `traduccion` = 'administrators ' WHERE `_traducciones`.`id` = 1011;
UPDATE `_traducciones` SET `traduccion` = 'anti_bacterie ' WHERE `_traducciones`.`id` = 337;
UPDATE `_traducciones` SET `traduccion` = 'anti_bruit ' WHERE `_traducciones`.`id` = 326;
UPDATE `_traducciones` SET `traduccion` = 'bb ' WHERE `_traducciones`.`id` = 1033;
UPDATE `_traducciones` SET `traduccion` = 'delete ' WHERE `_traducciones`.`id` = 250;
UPDATE `_traducciones` SET `traduccion` = 'borrarr ' WHERE `_traducciones`.`id` = 251;
UPDATE `_traducciones` SET `traduccion` = 'bte ' WHERE `_traducciones`.`id` = 320;
UPDATE `_traducciones` SET `traduccion` = 'search for ' WHERE `_traducciones`.`id` = 121;
UPDATE `_traducciones` SET `traduccion` = 'buscar_segun_estatus ' WHERE `_traducciones`.`id` = 266;
UPDATE `_traducciones` SET `traduccion` = 'c ' WHERE `_traducciones`.`id` = 297;
UPDATE `_traducciones` SET `traduccion` = 'change_clave ' WHERE `_traducciones`.`id` = 134;
UPDATE `_traducciones` SET `traduccion` = 'change_key ' WHERE `_traducciones`.`id` = 1452;
UPDATE `_traducciones` SET `traduccion` = 'change_clave_other ' WHERE `_traducciones`.`id` = 1028;
UPDATE `_traducciones` SET `traduccion` = 'change_estatus ' WHERE `_traducciones`.`id` = 265;
UPDATE `_traducciones` SET `traduccion` = 'change_idioma ' WHERE `_traducciones`.`id` = 1522;
UPDATE `_traducciones` SET `traduccion` = 'change_language ' WHERE `_traducciones`.`id` = 1240;
UPDATE `_traducciones` SET `traduccion` = 'change_language ' WHERE `_traducciones`.`id` = 1441;
UPDATE `_traducciones` SET `traduccion` = 'change_idioma ' WHERE `_traducciones`.`id` = 1492;
UPDATE `_traducciones` SET `traduccion` = 'centro ' WHERE `_traducciones`.`id` = 1380;
UPDATE `_traducciones` SET `traduccion` = 'centers ' WHERE `_traducciones`.`id` = 1012;
UPDATE `_traducciones` SET `traduccion` = 'city ' WHERE `_traducciones`.`id` = 1397;
UPDATE `_traducciones` SET `traduccion` = 'client ' WHERE `_traducciones`.`id` = 1378;
UPDATE `_traducciones` SET `traduccion` = 'customers ' WHERE `_traducciones`.`id` = 157;
UPDATE `_traducciones` SET `traduccion` = 'clientes_otros ' WHERE `_traducciones`.`id` = 1035;
UPDATE `_traducciones` SET `traduccion` = 'conduit_seul ' WHERE `_traducciones`.`id` = 329;
UPDATE `_traducciones` SET `traduccion` = 'coquille ' WHERE `_traducciones`.`id` = 328;
UPDATE `_traducciones` SET `traduccion` = 'cordon ' WHERE `_traducciones`.`id` = 340;
UPDATE `_traducciones` SET `traduccion` = 'coude_soupe ' WHERE `_traducciones`.`id` = 343;
UPDATE `_traducciones` SET `traduccion` = 'couleur_droite ' WHERE `_traducciones`.`id` = 310;
UPDATE `_traducciones` SET `traduccion` = 'couleur_gauche ' WHERE `_traducciones`.`id` = 307;
UPDATE `_traducciones` SET `traduccion` = 'create ' WHERE `_traducciones`.`id` = 34;
UPDATE `_traducciones` SET `traduccion` = 'custom_dume ' WHERE `_traducciones`.`id` = 323;
UPDATE `_traducciones` SET `traduccion` = 'sleep ' WHERE `_traducciones`.`id` = 325;
UPDATE `_traducciones` SET `traduccion` = 'du_number ' WHERE `_traducciones`.`id` = 304;
UPDATE `_traducciones` SET `traduccion` = 'lasts ' WHERE `_traducciones`.`id` = 319;
UPDATE `_traducciones` SET `traduccion` = 'edit ' WHERE `_traducciones`.`id` = 63;
UPDATE `_traducciones` SET `traduccion` = 'email ' WHERE `_traducciones`.`id` = 154;
UPDATE `_traducciones` SET `traduccion` = '' WHERE `_traducciones`.`id` = company 1379;
UPDATE `_traducciones` SET `traduccion` = 'epaulemnent ' WHERE `_traducciones`.`id` = 330;
UPDATE `_traducciones` SET `traduccion` = 'esss ' WHERE `_traducciones`.`id` = 236;
UPDATE `_traducciones` SET `traduccion` = 'export_cvs ' WHERE `_traducciones`.`id` = 675;
UPDATE `_traducciones` SET `traduccion` = 'export_google ' WHERE `_traducciones`.`id` = 1408;
UPDATE `_traducciones` SET `traduccion` = 'export_sql ' WHERE `_traducciones`.`id` = 1003;
UPDATE `_traducciones` SET `traduccion` = 'fil_nylon ' WHERE `_traducciones`.`id` = 342;
UPDATE `_traducciones` SET `traduccion` = 'folder-open ' WHERE `_traducciones`.`id` = 1409;
UPDATE `_traducciones` SET `traduccion` = '' WHERE `_traducciones`.`id` = manager 1013;
UPDATE `_traducciones` SET `traduccion` = 'grave ' WHERE `_traducciones`.`id` = 317;
UPDATE `_traducciones` SET `traduccion` = '' WHERE `_traducciones`.`id` = group 1398;
UPDATE `_traducciones` SET `traduccion` = 'hoka ' WHERE `_traducciones`.`id` = 339;
UPDATE `_traducciones` SET `traduccion` = 'home ' WHERE `_traducciones`.`id` = 11;
UPDATE `_traducciones` SET `traduccion` = 'home ' WHERE `_traducciones`.`id` = 1417;
UPDATE `_traducciones` SET `traduccion` = 'id ' WHERE `_traducciones`.`id` = 1396;
UPDATE `_traducciones` SET `traduccion` = 'implant ' WHERE `_traducciones`.`id` = 344;
UPDATE `_traducciones` SET `traduccion` = 'index ' WHERE `_traducciones`.`id` = 1498;
UPDATE `_traducciones` SET `traduccion` = 'index ' WHERE `_traducciones`.`id` = 12;
UPDATE `_traducciones` SET `traduccion` = 'index ' WHERE `_traducciones`.`id` = 1418;
UPDATE `_traducciones` SET `traduccion` = 'index ' WHERE `_traducciones`.`id` = 1468;
UPDATE `_traducciones` SET `traduccion` = 'info@mail.com ' WHERE `_traducciones`.`id` = 186;
UPDATE `_traducciones` SET `traduccion` = 'invisible ' WHERE `_traducciones`.`id` = 327;
UPDATE `_traducciones` SET `traduccion` = 'iros ' WHERE `_traducciones`.`id` = 332;
UPDATE `_traducciones` SET `traduccion` = 'legere ' WHERE `_traducciones`.`id` = 315;
UPDATE `_traducciones` SET `traduccion` = 'logs ' WHERE `_traducciones`.`id` = 293;
UPDATE `_traducciones` SET `traduccion` = 'logs, are created automatically, can not be created ' WHERE `_traducciones`.`id` = 1446;
UPDATE `_traducciones` SET `traduccion` = 'marques ' WHERE `_traducciones`.`id` = 308;
UPDATE `_traducciones` SET `traduccion` = 'mix ' WHERE `_traducciones`.`id` = 338;
UPDATE `_traducciones` SET `traduccion` = 'models ' WHERE `_traducciones`.`id` = 309;
UPDATE `_traducciones` SET `traduccion` = 'molle ' WHERE `_traducciones`.`id` = 318;
UPDATE `_traducciones` SET `traduccion` = 'moyenne ' WHERE `_traducciones`.`id` = 316;
UPDATE `_traducciones` SET `traduccion` = 'natation ' WHERE `_traducciones`.`id` = 324;
UPDATE `_traducciones` SET `traduccion` = 'notes ' WHERE `_traducciones`.`id` = 311;
UPDATE `_traducciones` SET `traduccion` = 'ok ' WHERE `_traducciones`.`id` = 1018;
UPDATE `_traducciones` SET `traduccion` = 'p ' WHERE `_traducciones`.`id` = 296;
UPDATE `_traducciones` SET `traduccion` = 'pailletes ' WHERE `_traducciones`.`id` = 341;
UPDATE `_traducciones` SET `traduccion` = 'payant ' WHERE `_traducciones`.`id` = 313;
UPDATE `_traducciones` SET `traduccion` = 'requests ' WHERE `_traducciones`.`id` = 1497;
UPDATE `_traducciones` SET `traduccion` = 'requests ' WHERE `_traducciones`.`id` = 24;
UPDATE `_traducciones` SET `traduccion` = 'requests ' WHERE `_traducciones`.`id` = 1420;
UPDATE `_traducciones` SET `traduccion` = 'requests ' WHERE `_traducciones`.`id` = 1467;
UPDATE `_traducciones` SET `traduccion` = 'customer requests ' WHERE `_traducciones`.`id` = 303;
UPDATE `_traducciones` SET `traduccion` = 'requests_email ' WHERE `_traducciones`.`id` = 300;
UPDATE `_traducciones` SET `traduccion` = 'company orders ' WHERE `_traducciones`.`id` = 302;
UPDATE `_traducciones` SET `traduccion` = 'requests for status ' WHERE `_traducciones`.`id` = 1036;
UPDATE `_traducciones` SET `traduccion` = 'requests_date ' WHERE `_traducciones`.`id` = 301;
UPDATE `_traducciones` SET `traduccion` = 'requests_id ' WHERE `_traducciones`.`id` = 1381;
UPDATE `_traducciones` SET `traduccion` = 'requests_notes ' WHERE `_traducciones`.`id` = 1403;
UPDATE `_traducciones` SET `traduccion` = 'requests_other ' WHERE `_traducciones`.`id` = 1037;
UPDATE `_traducciones` SET `traduccion` = 'requests_ref ' WHERE `_traducciones`.`id` = 299;
UPDATE `_traducciones` SET `traduccion` = 'permissions ' WHERE `_traducciones`.`id` = 1034;
UPDATE `_traducciones` SET `traduccion` = 'prince_de_crave ' WHERE `_traducciones`.`id` = 331;
UPDATE `_traducciones` SET `traduccion` = 'remake ' WHERE `_traducciones`.`id` = 314;
UPDATE `_traducciones` SET `traduccion` = 'resine ' WHERE `_traducciones`.`id` = 333;
UPDATE `_traducciones` SET `traduccion` = 'rite ' WHERE `_traducciones`.`id` = 321;
UPDATE `_traducciones` SET `traduccion` = 'root ' WHERE `_traducciones`.`id` = 1014;
UPDATE `_traducciones` SET `traduccion` = 'silicone ' WHERE `_traducciones`.`id` = 334;
UPDATE `_traducciones` SET `traduccion` = 'without permission ' WHERE `_traducciones`.`id` = 283;
UPDATE `_traducciones` SET `traduccion` = 'slim_tube ' WHERE `_traducciones`.`id` = 322;
UPDATE `_traducciones` SET `traduccion` = 't_usuarios ' WHERE `_traducciones`.`id` = 242;
UPDATE `_traducciones` SET `traduccion` = 'thermosoft ' WHERE `_traducciones`.`id` = 336;
UPDATE `_traducciones` SET `traduccion` = 'thermotec ' WHERE `_traducciones`.`id` = 335;
UPDATE `_traducciones` SET `traduccion` = 'txt ' WHERE `_traducciones`.`id` = 156;
UPDATE `_traducciones` SET `traduccion` = 'users ' WHERE `_traducciones`.`id` = 133;
UPDATE `_traducciones` SET `traduccion` = 'sellers ' WHERE `_traducciones`.`id` = 1239;
UPDATE `_traducciones` SET `traduccion` = 'ventilation_droite ' WHERE `_traducciones`.`id` = 306;
UPDATE `_traducciones` SET `traduccion` = 'ventilation_gauche ' WHERE `_traducciones`.`id` = 305;
UPDATE `_traducciones` SET `traduccion` = 'see ' WHERE `_traducciones`.`id` = 129;
UPDATE `_traducciones` SET `traduccion` = 'xx_XX ' WHERE `_traducciones`.`id` = 148;
UPDATE `_traducciones` SET `traduccion` = 'Last login ' WHERE `_traducciones`.`id` = 1394;